### ISSUE TITLE
new rule prefer-jsdoc

### ISSUE THREAD

**Issue by tjx666** [gajus/eslint-plugin-jsdoc#1002]
## Motivation

jsdoc can provide useful documentation with IDE integration.

## Current behavior

case one: object property

```javascript
const person = {
    name: 'ly',
    // some description op top of property
    age: 18, // some description after property
};
```

case 2: typescript interface, should also work for type, enum

```typescript
interface Options {
    // default value is ['.js', '.ts']
    extensions: String[]; // default value is ['.js', '.ts']
}
```

case 3: function

```javascript
// compute sum of two numbers
function add(a, b) {
    
}
```

## Desired behavior

all single comments above should be replaced with jsdoc

**Comment by thernstig** [comment]
@tjx666 @brettz9 isn't this what https://eslint.org/docs/latest/rules/multiline-comment-style does already? That could be enforced there.

**Comment by brettz9** [comment]
@thernstig : While that might make sense as a host for the behavior, that rule looks like it converts line comments to block comments (including the conventionally asterisked lines) but doesn't convert any comments to JSDoc-style comments (which must have the 2 asterisks at the beginning).

**Comment by tjx666** [comment]
block comment:

```javascript
/* this is a
block 
comment */
```

jsdoc: start withs `/**`, and will be parsed by typescript:

```javascript
/**this is
jsdoc
comment */

```

**Comment by brettz9** [comment]
@tjx666 : I'd suggest asking for this feature within `multiline-comment-style` even though that rule doesn't offer the option currently

**Comment by tjx666** [comment]
@brettz9 I think this rule is complex enough and I can't find rule `multiline-comment-styl`

**Comment by brettz9** [comment]
I'm suggesting requesting this feature from ESLint itself.

**Comment by tjx666** [comment]
Seems eslint self doesn't accept feature other than ECMAScript new syntax

**Comment by brettz9** [comment]
Ok, yeah, thanks for checking.

**Comment by brettz9** [comment]
Filed #1256 . Care to take a look, @tjx666 ?

**Comment by brettz9** [comment]
I've noted that the new rule is experimental (and it's not under recommended), but it now includes options to check before, after, or before and after. I expect the rule (or the `@es-joy/jsdoccomment` code it depends upon) will need some further tweaking, but it handles the use cases mentioned.
