### ISSUE TITLE
`typeAnnotation` can be undefined

### ISSUE THREAD

**Issue by RebeccaStevens** [gajus/eslint-plugin-jsdoc#1008]
On this line:

https://github.com/gajus/eslint-plugin-jsdoc/blob/f1bf68f9e5a8b8632e1978bcf5a3f8123fb64ba3/src/jsdocUtils.js#L138

`typeAnnotation` (the first one) can be `undefined`. When it is it cause a crash.

**Comment by brettz9** [comment]
Thank you. Do you have a minimal case where it can cause the crash (even if it is not completely functional code)?

**Comment by RebeccaStevens** [comment]
Here's a failing workflow: https://github.com/RebeccaStevens/is-immutable-type/actions/runs/4562439665/jobs/8049654541
Caused by this code: https://github.com/RebeccaStevens/is-immutable-type/blob/d750cde51338f58437268c219991be68ad476195/src/calculate.ts#LL103-L110C18

**Comment by brettz9** [comment]
I could not replicate as it seems for my environment, `typeAnnotation` is not `in` the object at all, but since as you point out, `typeAnnotation` can apparently be present but `undefined`, I've applied a fix.
