### ISSUE TITLE
Full ESLint on JavaScript within @example

### ISSUE THREAD

**Issue by brettz9** [gajus/eslint-plugin-jsdoc#101]
How easy would it be to add support for linting @example code (e.g., as with Github fenced blocks flagging "js" as the language)?

I see from the JSDoc source that "prettyprint" is added for @example. (Highlighting also applies for source and details (of methods and such), but this should not be needed again for user code; there is also the markdown highlighter though I think that code only applies to the tutorials and such that it can embed, and not fenced blocks or such.)

It'd be a bonus if there could also be the ability to indicate, either with an object with rules, a separate config file, or with the rules of the same file applied but with specific "overrides" applied (e.g., so that the examples within JSDoc comments may follow the same looser rules as say one's ".md" files as opposed to ".js" files)?

Would this be doable?

**Comment by gajus** [comment]
It is definitely doable.

Seems very esoteric, though.

I would accept a PR, but thats not something I would attempt myself.
