### ISSUE TITLE
`no-empty-blocks` rule

### ISSUE THREAD

**Issue by Dimava** [gajus/eslint-plugin-jsdoc#1042]
## Motivation

1. I'm moving some JS code with types described as JSDoc into TS
All those param types are being removed and become empty
Making all the functions to have descriptions is not planned.
Thus I need a way to cleanup empty code blocks.
2. I'm working on https://github.com/Shinigami92/eslint-define-config
Code generation sometimes causes empty JSDoc blocks to appear here and there.
Some non-needed blocks like `@minItems` can also appear.

I am looking for an easy and straigntforward way to remove the blocks I don't need
First step would be removing unwanted tags by autofixer
Second step would be removing blocks which became empty by autofixer

## Current behavior

The documentation is too long to read it completely
Nothing searchable there clearly states that it can be used to remove lines or blocks, other then builtin autofixers

## Desired behavior

- A rule that says that it bans empty blocks in its name
- A rule that says that it bans certain tags in its name

## Alternatives considered

I have spend an hour reading documentation, understood nothing on the case

**Comment by brettz9** [comment]
The removal of empty tags is a nice idea for a rule.

`check-tag-names` can be used to block tags, either if you don't use `definedTags` with a rule and a tag isn't part of the official expected  set, or if you blacklist tags you wish to block like this:

```js
settings: {
        jsdoc: {
          tagNamePreference: {
            todo: false,
          },
        },
      },
```

Although it is discussed under settings, it would be good to mention this explicitly under `check-tag-names` beyond just referring to the setting. A PR for an addition to `check-tag-names` would be welcome.
