### ISSUE TITLE
Logical OR assignment (||=) operator

### ISSUE THREAD

**Issue by mtrezza** [gajus/eslint-plugin-jsdoc#1055]
## Issue

It seems that Node 14 support has been dropped in https://github.com/gajus/eslint-plugin-jsdoc/pull/1034. However, it seems the release was only a patch version `43.1.1`. Dropping Node 14 support is actually a breaking change, requiring a major release (if following semver), and the package indeed [fails](https://github.com/parse-community/Parse-SDK-JS/actions/runs/4823950914/jobs/8593115917?pr=1873) on Node 14.21.1.

## Solution

I guess there isn't a great retrospect solution, but I wanted to point this out for future changes in supported Node versions.

## Environment

- Node version: Node 14.21.1
- ESLint version n/a
- `eslint-plugin-jsdoc` version: 43.1.1.

**Comment by brettz9** [comment]
Yes, apologies for that. Will try to watch out better in the future.
