### ISSUE TITLE
`jsdoc/require-hyphen-before-param-description` not fixing all auto-fixable problems

### ISSUE THREAD

**Issue by thernstig** [gajus/eslint-plugin-jsdoc#1074]
## Expected behavior
I expect `jsdoc/require-hyphen-before-param-description` to auto-fix all problems.

## Actual behavior

It does not remove the hyphen before returns in all scenarios. See example below.

## ESLint Config

```js
{
  "root": true,
  "reportUnusedDisableDirectives": true,
  "parserOptions": {
    "ecmaVersion": 2023,
    "sourceType": "module"
  },
  "env": {
    "node": true,
    "es2022": true,
  },
  "extends": [
    "plugin:jsdoc/recommended-error"
  ],
  "rules": {
    "jsdoc/require-jsdoc": "off",
    "jsdoc/require-description": "error",
    "jsdoc/check-syntax": "error",
    "jsdoc/check-line-alignment": ["error", "never", { "wrapIndent": "    " }],
    "jsdoc/require-hyphen-before-param-description": [
      "error",
      "always",
      {
        "tags": {
          "*": "never",
          "property": "always"
        }
      }
    ],
    "jsdoc/require-asterisk-prefix": "error",
    "jsdoc/sort-tags": [
      "error",
      {
        "tagSequence": [
          {
            "tags": [
              "since",
              "deprecated",
              "access",
              "public",
              "protected",
              "private"
            ]
          },
          { "tags": ["class", "augments", "mixes"] },
          { "tags": ["alias", "memberof"] },
          { "tags": ["see", "link", "global"] },
          { "tags": ["-other"] },
          { "tags": ["listens"] },
          { "tags": ["param"] },
          { "tags": ["throws"] },
          { "tags": ["fires"] },
          { "tags": ["yields"] },
          { "tags": ["returns"] },
          { "tags": ["example"] }
        ]
      }
    ],
    "jsdoc/tag-lines": ["error", "any", { "startLines": 1 }],
    "jsdoc/no-bad-blocks": ["error", { "preventAllMultiAsteriskBlocks": true }],
    "jsdoc/no-blank-blocks": ["error", { "enableFixer": true }]
  }
}

```

## ESLint sample

```js
/**
 * Split a unit to metric prefix and basic unit.
 *
 * @param {string} unit - Unit to split.
 * @param {string} [basicUnit] - Basic unit regardless of the metric prefix.
 *     If omitted, basic unit will be inferred by trying to remove the metric
 *     prefix in `unit`.
 *
 * @returns {{ prefix: string, basicUnit: string }} - Split result.
 *     If `unit` does not have a metric prefix, `''` is returned for `prefix`.
 *     If `unit` does not have a basic unit, `''` is returned for `basicUnit`.
 */
```

## Environment

- Node version: v18.14.2
- ESLint version v8.31.0
- `eslint-plugin-jsdoc` version: 44.0.2

**Comment by brettz9** [comment]
> I even noticed something even stranger now. It cannot fix the `@param`

You have `always` set for the string setting. This is what is applied to `@param`.

**Comment by brettz9** [comment]
As far as the `@returns`, what appears to be going on here is that the fixer looks through the description for hyphens to remove and finds them in the param and removes them instead (but they are added back). This rule's fixer predates our ability to use parsing to more precisely find the relevant text and replace it.

**Comment by thernstig** [comment]
> > I even noticed something even stranger now. It cannot fix the `@param`
> 
> You have `always` set for the string setting. This is what is applied to `@param`.

`always` is supposed to add a hyphen, right? The code I showcased above was not fixed to add a hyhpen.

**Comment by brettz9** [comment]
Ok, I see, but have you tested again against the latest version? Seems to be working to add the hyphen for the param if the `@returns` one is taken care of as it should

**Comment by thernstig** [comment]
Tested with the latest release, and it seemed to solve all problems. Even the strange one with `@param`. I will open a new case if I find more issues.
