### ISSUE TITLE
Rules contain `{"gitdown": "contents", "rootId": "no-undefined-types"}` at the top

### ISSUE THREAD

**Issue by thernstig** [gajus/eslint-plugin-jsdoc#1077]
Check e.g. https://github.com/gajus/eslint-plugin-jsdoc/blob/52119a59e70d2d255e0f475f0fcd0bf780d0acd2/.README/rules/no-undefined-types.md

I assume this is not supposed to be like that?

**Comment by brettz9** [comment]
Those are the source files. You can see the built files in the `/docs` directory, e.g., https://github.com/gajus/eslint-plugin-jsdoc/blob/52119a59e70d2d255e0f475f0fcd0bf780d0acd2/docs/rules/no-undefined-types.md

**Comment by thernstig** [comment]
Apologize about this issue then.

**Comment by brettz9** [comment]
It's all good, no worries!
