### ISSUE TITLE
meta.doc.url is pointing to an old url

### ISSUE THREAD

**Issue by HolgerJeromin** [gajus/eslint-plugin-jsdoc#1094]
Since #1049 we have different urls for every rule. 🎉
But the links of all urls were missed in this PR.

https://github.com/gajus/eslint-plugin-jsdoc/blob/6824ab6cb3e81262798abd04bd147883554cd141/src/rules/noTypes.js#L38

## Expected behavior
Link in VS eslint reporting should open the correct documentation but uses outdated link.

## Environment
- `eslint-plugin-jsdoc` version: v44.2.5

**Comment by HolgerJeromin** [comment]
Impressive speed. Thanks!

**Comment by HolgerJeromin** [comment]
By looking at https://github.com/gajus/eslint-plugin-jsdoc/tree/main/src/rules
I found that
https://github.com/gajus/eslint-plugin-jsdoc/blob/main/src/rules/requireAsteriskPrefix.js
and 
https://github.com/gajus/eslint-plugin-jsdoc/blob/main/src/rules/informativeDocs.js
are not hit by your script. 
The whole meta part is missing for both...

**Comment by brettz9** [comment]
Thanks for the reports, and sorry about the missed items--updated in #1096 which should be released shortly.
