### ISSUE TITLE
@types/eslint-plugin-jsdoc or bundle .d.ts

### ISSUE THREAD

**Issue by snebjorn** [gajus/eslint-plugin-jsdoc#1130]
## Motivation

With the new ESLint flat config we import plugins

```js
import jsdoc from "eslint-plugin-jsdoc";
```
However that causes typescript in the VSCode to report an error due to missing type definitions.

> Could not find a declaration file for module 'eslint-plugin-jsdoc'. 'myrepo/node_modules/eslint-plugin-jsdoc/dist/index.js' implicitly has an 'any' type.
>  Try `npm i --save-dev @types/eslint-plugin-jsdoc` if it exists or add a new declaration (.d.ts) file containing `declare module 'eslint-plugin-jsdoc';`

## Current behavior

There are no types for eslint-plugin-jsdoc

## Desired behavior

`eslint-plugin-jsdoc` should bundle the typescript types.

I'm not sure this is correct, but here's an example of the d.ts

```ts
import type { ESLint } from "eslint";

interface JSDoc extends ESLint.Plugin {
  configs: ESLint.Plugin["configs"] & {
    recommended: ESLint.ConfigData;
    ["recommended-error"]: ESLint.ConfigData;
    ["recommended-typescript"]: ESLint.ConfigData;
    ["recommended-typescript-error"]: ESLint.ConfigData;
    ["recommended-typescript-flavor"]: ESLint.ConfigData;
    ["recommended-typescript-flavor-error"]: ESLint.ConfigData;
  };
}

export default JSDoc;
```

## Alternatives considered

A DefinitelyTyped package `@types/eslint-plugin-jsdoc`

**Comment by snebjorn** [comment]
#1139 added
https://github.com/gajus/eslint-plugin-jsdoc/blob/e8b14756c573bc7f6eb824f2e87b67bbd6a50fab/package.json#L86
but index.d.ts is missing from the distributed package

![image](https://github.com/gajus/eslint-plugin-jsdoc/assets/1266245/ebc2f409-3c82-4776-8b0d-e1897c7ebff1)

**Comment by paulshryock** [comment]
> but **index.d.ts** is missing from the distributed package

That's because `*.d.ts` is explicitly ignored in [`.npmignore`](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/.npmignore#L9).

Looks like `.npmignore` should be updated to to not ignore `index.d.ts`.

**Comment by brettz9** [comment]
Yes, sorry, I inadvertently actually added that when merely considering adding it.

I'm afraid that with some projects rather conscious about package size, that the multiple generated files may become cumbersome for some.

We could submit this to DefinitelyTyped, as you say, using what we're already able to generate.

**Comment by snebjorn** [comment]
I don't understand why package size matters for a dev dependency - unless it's ridiculously large 😃 

How big are the types? For comparison `@typescript-eslint`'s types are 7 KB including .d.ts.map and 3.66 KB without. I'm not counting the AST types, as it doesn't seem relevant to using the package for linting.

Anyway, types [bundled in the package is optimal](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) but publishing a separate types package or via DefinitelyTyped also works 📦

**Comment by brettz9** [comment]
For our project, it's 76 KB / 49 KB (with and without map files).

I am also unclear on why it should matter (IDEs which rely on linting tools perhaps?), but it really apparently does given how much attention projects have given us to package size (#1141 being only the most recent). I'm not keen to garner complaints on this (especially when typing is not really so critical for ESLint config files, beyond suppressing complaints in IDEs) and then having to yank the new typing feature from those who do want it.

While there are some who consider it an anti-pattern to publish within the package due to semver noise, I personally prefer it myself (projects ideally shouldn't need to track transitive dependencies themselves), but feel it is unfortunately necessary at this point.

**Comment by what1s1ove** [comment]
Hey guys!

Since Eslint 9 is on the horizon, I think it's essential to pay more attention to this issue and start preparing for the changes 🙏

<img width="1036" alt="image" src="https://github.com/gajus/eslint-plugin-jsdoc/assets/42296182/3d7766a0-96d6-433a-9d75-8cc2ce8c2add">

**Comment by brettz9** [comment]
I've submitted #1180 which should do the trick. It appears that it will be sufficient and feasible to only publish the index file types.

**Comment by what1s1ove** [comment]
> I've submitted #1180 which should do the trick. It appears that it will be sufficient and feasible to only publish the index file types.

Thank you so much!

**Comment by brettz9** [comment]
If someone wouldn't mind letting us how it goes...

**Comment by what1s1ove** [comment]
> If someone wouldn't mind letting us how it goes...

This is definitely better, but still requires type casting, as index signatures are used.

<img width="523" alt="image" src="https://github.com/gajus/eslint-plugin-jsdoc/assets/42296182/7a216a2b-3dbc-4a41-b4c2-8c01fe85265a">

Here is the final result:

<img width="435" alt="image" src="https://github.com/gajus/eslint-plugin-jsdoc/assets/42296182/f5ecb694-370d-41bc-9472-30a29a143b49">

Perhaps you would like to make the keys explicit, as is done in the native recommended ESLint plugin:

<img width="558" alt="image" src="https://github.com/gajus/eslint-plugin-jsdoc/assets/42296182/37567e92-e8a5-4488-8daf-62a29e3f7b43">

In your case

```
declare const index: import('eslint').ESLint.Plugin & {
    // and all other configs
    configs: Record<'flat/recommended', 'recommended-typescript-flavor', import('eslint').ESLint.ConfigData | {}>;
};
```

**Comment by brettz9** [comment]
Should be fixed now in #1181 (and released in v47.0.1).

**Comment by what1s1ove** [comment]
> Should be fixed now in #1181 (and released in v47.0.1).

<img width="451" alt="image" src="https://github.com/gajus/eslint-plugin-jsdoc/assets/42296182/5418acb9-a980-475d-a4c5-9ca5dfaad2bc">

Another error 🥲 Why is an empty object needed here?

<img width="1368" alt="image" src="https://github.com/gajus/eslint-plugin-jsdoc/assets/42296182/45b52794-8830-48b7-a776-13d32ccab0f5">

**Comment by brettz9** [comment]
Will users really need to get at `rules` like that? That `{}` is, IIRC, fudging things to avoid complaints about `plugins: ["old-style-strings"]`.

**Comment by what1s1ove** [comment]
> Will users really need to get at `rules` like that? That `{}` is, IIRC, fudging things to avoid complaints about `plugins: ["old-style-strings"]`.


I modified it to the version recommended in the README (https://www.npmjs.com/package/eslint-plugin-jsdoc), and now it works 🎉 But honestly, I'm not very fond of how it looks now 😁

<img width="1260" alt="image" src="https://github.com/gajus/eslint-plugin-jsdoc/assets/42296182/8fae1ee6-e75c-4ac7-a909-b3f43a5b10e5">

My other plugins look like this... but so far, ESLint itself doesn't know how to better incorporate them 😅

<img width="394" alt="image" src="https://github.com/gajus/eslint-plugin-jsdoc/assets/42296182/e5c91605-3f79-4b21-84a7-c409dcfd9e00">

**Comment by brettz9** [comment]
The problem with the latter is that the plugins themselves need to be reworked for flat config. A bit of a mess...

**Comment by what1s1ove** [comment]
> The problem with the latter is that the plugins themselves need to be reworked for flat config. A bit of a mess...

As of now, I think everything is great, thank you for all you do!

**Comment by Logicer16** [comment]
Just tried to use it but it seems we've incorrectly used `ConfigData` instead of `FlatConfig` for the flat configs.

```
error TS2322: Type '{} | ConfigData<RulesRecord>' is not assignable to type 'FlatConfig'.
  Type 'ConfigData<RulesRecord>' is not assignable to type 'FlatConfig'.
    Types of property 'plugins' are incompatible.
      Type 'string[] | undefined' is not assignable to type 'Record<string, Plugin> | undefined'.
        Type 'string[]' is not assignable to type 'Record<string, Plugin>'.
          Index signature for type 'string' is missing in type 'string[]'.
```

**Comment by Logicer16** [comment]
I'm also experiencing a ["double-`default`"](https://github.com/microsoft/TypeScript/issues/50058#issuecomment-1404411380) issue when I have `"moduleResolution": "NodeNext"` in my `tsconfig.json`. This is **just an issue with the types**; runtime continues to work as expected. I am currently working around the issue with `"moduleResolution": "Bundler"`.

**Comment by brettz9** [comment]
> Just tried to use it but it seems we've incorrectly used `ConfigData` instead of `FlatConfig` for the flat configs.

Ah yes, you're right. Fix should be applied shortly.

> I'm also experiencing a ["double-`default`"](https://github.com/microsoft/TypeScript/issues/50058#issuecomment-1404411380) issue when I have `"moduleResolution": "NodeNext"` in my `tsconfig.json`. This is **just an issue with the types**; runtime continues to work as expected. I am currently working around the issue with `"moduleResolution": "Bundler"`.

Can you indicate where you're seeing the error when you don't change the `moduleResolution`?

**Comment by Logicer16** [comment]
> Can you indicate where you're seeing the error when you don't change the `moduleResolution`?

```
src/index.ts:4:46 - error TS2339: Property 'configs' does not exist on type 'typeof import("~/Developer/a/node_modules/eslint-plugin-jsdoc/dist/index")'.

4 const jsdocConfig: Linter.FlatConfig = jsdoc.configs[
                                               ~~~~~~~
```

This builds without issue:

```ts
const jsdocConfig: Linter.FlatConfig = jsdoc.default.configs[
  "flat/recommended-typescript-flavor-error"
];
```

But fails at runtime:

```
const jsdocConfig = jsdoc.default.configs["flat/recommended-typescript-flavor-error"];
                                  ^

TypeError: Cannot read properties of undefined (reading 'configs')
    at file:///Users/jamesross/Developer/a/dist/index.js:2:35
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.10.0
```

If you need help reproducing, the following files are all it seems to need for the error to occur.

<details>
<summary><code>src/index.ts</code></summary>

```ts
import jsdoc from "eslint-plugin-jsdoc";
import {Linter} from "eslint";

const jsdocConfig: Linter.FlatConfig = jsdoc.configs[
  "flat/recommended-typescript-flavor-error"
];
```

</details>

<details>
<summary><code>package.json</code></summary>

```json
{
  "name": "a",
  "version": "1.0.0",
  "main": "index.js",
  "type": "module",
  "devDependencies": {
    "eslint": "^8.56.0",
    "eslint-plugin-jsdoc": "^47.0.2",
    "typescript": "^5.3.3"
  }
}
```

</details>

<details>
<summary><code>tsconfig.json</code></summary>

```json
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "outDir": "dist"
  }
}
```

</details>

**Comment by brettz9** [comment]
Hmmm... I've confirmed the issue with your sample, but for some reason, we don't see the problem in regular "JavaScript-with-JSDoc-as-TypeScript" mode.

Adding the following to a JavaScript file:

```js
import jsdoc from "eslint-plugin-jsdoc";

jsdoc.configs[
  "flat/recommended-typescript-flavor-error"
];
```
shows up with tooltip info properly:

<img width="829" alt="image" src="https://github.com/gajus/eslint-plugin-jsdoc/assets/20234/c1d39917-d856-4f0f-aa28-d3034bb034dd">

**Comment by brettz9** [comment]
It appears it can be fixed by our switching to native ESM (with fallback to CJS).

**Comment by what1s1ove** [comment]
Hey @brettz9, all

Now it looks perfect! Thank you for all you do! Here is my migration pull request -https://github.com/what1s1ove/whatislove.dev/pull/298

**Comment by brettz9** [comment]
> > Can you indicate where you're seeing the error when you don't change the `moduleResolution`?
> 
> ```
> src/index.ts:4:46 - error TS2339: Property 'configs' does not exist on type 'typeof import("~/Developer/a/node_modules/eslint-plugin-jsdoc/dist/index")'.
> 
> 4 const jsdocConfig: Linter.FlatConfig = jsdoc.configs[
>                                                ~~~~~~~
> ```

Try release v48.0.1

**Comment by Logicer16** [comment]
> Try release v48.0.1

Sorry for the silence, just got around to checking and everything now seems to be working as expected. Thank you so much for all your work.
