### ISSUE TITLE
Force consistent object typedef

### ISSUE THREAD

**Issue by remcohaszing** [gajus/eslint-plugin-jsdoc#1140]
## Motivation

There are 3 ways to define object type defs (that I know of):

```js
/**
 * @typedef Person
 * @property name
 */

/**
 * @typedef {object} Person
 * @property name
 */

/**
 * @typedef {Object} Person
 * @property name
 */
```

I would like to enforce one consistently. Personally I prefer the first variant.

## Current behavior

N/A

## Desired behavior

A new ESLint rule to enforce a consistent way to write object typedefs.

```jsonc
{
  "rules": {
    "jsdoc/object-style": [
      "error",
      // Default value
      null // or "object" or "Object"
    ]
  }
}
```

## Alternatives considered

The name can be different. The options can be different.

**Comment by brettz9** [comment]
I would suggest just using `jsdoc/no-restricted-syntax`. This won't have a fixer, but it can report the non-desired configurations. Look for the examples using `JsdocTag`.

**Comment by remcohaszing** [comment]
Thanks for the suggestion! This works for me:

```js
module.exports = {
  rules: {
    'jsdoc/no-restricted-syntax': [
      'error',
      {
        contexts: [
          {
            comment: 'JsdocBlock:has(JsdocTag[tag=typedef][parsedType.value=/object/i])',
            message: 'Omit the object type from typedef'
          }
        ]
      }
    ]
  }
}
```
