### ISSUE TITLE
SyntaxError: Unexpected token '||='

### ISSUE THREAD

**Issue by dplewis** [gajus/eslint-plugin-jsdoc#1151]
I know that Node 14 has been dropped but other high level features have been reverted like https://github.com/gajus/eslint-plugin-jsdoc/pull/1149

```
/node_modules/eslint-plugin-jsdoc/dist/rules/informativeDocs.js:95
    descriptionReported ||= tag.description === description && /** @type {import('comment-parser').Spec & {line: import('../iterateJsdoc.js').Integer}} */
```

## Environment

- Node version: 14.21.1
- ESLint version 8.40.0
- `eslint-plugin-jsdoc` version: 46.5.1

**Comment by brettz9** [comment]
Sorry, that was for the sake of Node 16. Node 16+ are the currently supported versions, so closing.

**Comment by dplewis** [comment]
No problem, I understand
