### ISSUE TITLE
[check-param-names] Error: "Cannot destructure property 'lines' of 'sourceCode'"

### ISSUE THREAD

**Issue by simon-abbott** [gajus/eslint-plugin-jsdoc#1159]
## Expected behavior

The rule should run properly.

## Actual behavior

ESLint crashes with the error `TypeError: Error while loading rule 'jsdoc/check-param-names': Cannot destructure property 'lines' of 'sourceCode' as it is undefined.`

## ESLint Config

```json
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true,
      "impliedStrict": true
    },
    "warnOnUnsupportedTypeScriptVersion": true,
    "requireConfigFile": false,
    "allowImportExportEverywhere": true,
    "babelOptions": {
      "presets": ["next/babel"],
      "caller": {
        "supportsTopLevelAwait": true
      }
    },
    "ecmaVersion": "latest",
    "project": "./tsconfig.json"
  },
  "plugins": ["jsdoc"],
  "rules": {
    "jsdoc/check-param-names": ["error"]
  }
}
```

## ESLint sample

```ts
const foo = "";
```

## Environment

- Node version: 18.14.0
- ESLint version 8.38.0
- `eslint-plugin-jsdoc` version: 46.8.1

**Comment by simon-abbott** [comment]
I tested 46.7.0 as well, and that worked just fine. I suspect it's an issue with 8dbcb6f31d8e75b6a12dc0cfa19ace736ed0e9c6.

**Comment by brettz9** [comment]
The method `getSourceCode` was deprecated and can be avoided in more recent versions of ESLint, but apparently the replacement hasn't been around for very long.
