### ISSUE TITLE
require-jsdoc fixer: Insert default comment instead of empty

### ISSUE THREAD

**Issue by btxtiger** [gajus/eslint-plugin-jsdoc#1163]
## Motivation

I am using `require-jsdoc` to mark an error if a function is missing a comment.
<img width="353" alt="image" src="https://github.com/gajus/eslint-plugin-jsdoc/assets/15804690/43532ad6-9e69-4fe9-bf7e-96627843d2e8">

## Current behavior

When running the autofix, it will add an empty comment which is still no considered to be valid.
<img width="388" alt="image" src="https://github.com/gajus/eslint-plugin-jsdoc/assets/15804690/bd2cf45d-1115-4977-8d47-928196f35201">

## Desired behavior

When running the autofix, it should insert a configurable default comment, which fixes the error entirely, by defining a default text. This also helps to find the undocumented functions later in the IDE search.

<img width="449" alt="image" src="https://github.com/gajus/eslint-plugin-jsdoc/assets/15804690/f3ac9192-5811-43ae-8e1b-0497759f1f5e">

**Comment by brettz9** [comment]
One alternative is to use `no-missing-syntax` to find empty comment blocks (after they have been auto-inserted):

```js
  'jsdoc/no-missing-syntax': ['error', {
    contexts: [
      {
        comment: 'JsdocBlock[tags.length=0][description=""]',
        context: 'FunctionDeclaration',
      },
    ],
  }]
```

**Comment by brettz9** [comment]
I had forgotten there already is an option for `jsdoc/require-jsdoc` that allows adding your own custom message. Use the now documented `fixerMessage` option.

Closing as that should resolve, but feel free to comment further as needed.
