### ISSUE TITLE
Require jsdoc only for everything exported from a specific file

### ISSUE THREAD

**Issue by ashwinGokhale** [gajus/eslint-plugin-jsdoc#1200]
## Motivation

We have an [Nx](https://nx.dev/) monorepo where the public API for libraries are defined in a single file: `libs/path/to/lib/src/index.ts`. 
The `publicOnly` option for the `jsdoc/require-jsdoc` rule does not allow me to specify where the public API is defined.

## Current behavior

The `publicOnly` option only checks if it is exported in general.

## Desired behavior

The `publicOnly` option lets me specify a list of files that define my public API and only checks the ones explicitly exported from those files.

**Comment by brettz9** [comment]
To apply ESLint rules like `eslint-plugin-jsdoc` to particular files, you can use [`overrides`](https://eslint.org/docs/latest/use/configure/configuration-files#how-do-overrides-work), or if you are using the new flat config, just add a new [top-level object with its own `files` array](https://eslint.org/docs/latest/use/configure/configuration-files-new#using-plugin-rules).

Closing as this should resolve, though feel free to comment further as needed.

**Comment by ashwinGokhale** [comment]
Hi @brettz9 adding the overrides for only the `src/lib/index.ts` file does not solve my problem. Here is a [small example](https://eslint-online-playground.netlify.app/#eNqVUk1P9CAQ/iukl2pe3b3vxjcxrt6MF+NFPFA6qyiFOlBds+l/d4BiW6NRmzQt83wNMPvCoVxqVS3F4tEVq0I1rUXP9qxiPduibVi5WFaEldxwA7uISmucZ4KdsINDdvKflaJk/1h1cLjmpjiKlsrUsEuWg2hPgtEyR5ZrjuRM78x7a+3oXglMtME7aENLo3cSVRNJuSbyApxWxqMksjVE33PDGCeVB1M7XqzYLa0iaYUgbdNQHWpe3B0lZqu7e2Uy89HVVk5AgQ7wqvWK4gMl2scA2YgbQEdAqPNCCw/O8yIqA8PZDiVcv7WQCI2tO03/Ae8Hf6TK6BuqqW5fAFHVCbtNjkN0gLdqkFHH06vIjSfW3DxX4w6XCM+dQjge9vsRklkUb/FjM+mZ2CRS21VaySuj34KDxw5m/NhDyvnURUZPKeX1ojMynO/5rkVw+UC/cAuKMy2c24DUAkUQ/UT9lemfOrgE/2DrDWyVUdMO5sx+upws7vLvUIsfKvY0y62QT+IePk1yDS8baMPQGqlm95nn+pv5S+Bxmu/xokdmHLkQ3b8DiTE+LA==) to show to problem. In this example the `foo` function has an error (which is expected), but the `a` function does not. I would expect the `a` function to have an error because I export it from `src/lib/index.js`.

**Comment by brettz9** [comment]
ESLint is, unfortunately, only aware of a single file at a time.

Perhaps documenting the export statement itself would work for you (e.g., adding `ExportNamedDeclaration` to the contexts and requiring a comment block above that)?

**Comment by ashwinGokhale** [comment]
@brettz9 That won't work either because it doesn't catch `export *` syntax. Is there a way to specify the public API files in the publicOnly option and cross check with the exports in those files?
