### ISSUE TITLE
Rule to limit the number of main tags per comment block

### ISSUE THREAD

**Issue by Ploppy3** [gajus/eslint-plugin-jsdoc#1207]
## Motivation

There should be only 1 `@typedef` per comment block.

## Current behavior

But there is no rule to limit this, therefore it can lead to invalid jsdoc.

## Desired behavior

Add a new rules which limits the number of "main" tags (such as `@typedef`) that can be used in a single comment block.
This could be autofixed by closing and opening another comment block.

Example: 

Change:
```js
/**
 * @typedef {object} Test1
 * @property {string} prop1
 * @typedef {object} Test2
 * @property {string} prop2
 */
```

Into: 
```js
/**
 * @typedef {object} Test1
 * @property {string} prop1
 */
/**
 * @typedef {object} Test2
 * @property {string} prop2
 */
```

**Comment by brettz9** [comment]
You can currently do so as follows:

```js
rules: {
  'jsdoc/no-restricted-syntax': ['error', {
    contexts: [
      {
        comment: 'JsdocBlock:has(JsdocTag[tag=typedef] ~ JsdocTag[tag=typedef])',
        context: 'any',
        message: 'No multiple typedefs within a single block; create a separate block',
      },
    ],
  }]
}
```

**Comment by Ploppy3** [comment]
Thank you very much, it works, feel free to close it if necessary
