### ISSUE TITLE
Line break before JSDoc blocks

### ISSUE THREAD

**Issue by thernstig** [gajus/eslint-plugin-jsdoc#1209]
## Motivation

It would be nice to always force line breaks before `/**` blocks as code reads nicer that way, akin to chapters in a book.

## Current behavior

There is no such rule.

## Desired behavior

To add such rule.

## Alternatives considered

https://eslint.style/rules/js/lines-around-comment exists, and maybe I should use that instead? But I wrote this anyway as this package is about specifically JSDoc. I am fine however to use https://eslint.style/rules/js/lines-around-comment if there is no interest to include it here.

**Comment by lamuertepeluda** [comment]
Using this with prettier is at least trickier. It should have been disabled by default

**Comment by thernstig** [comment]
@lamuertepeluda I have not updated to test the new rule yet, but when I wrote these we were using Prettier (and still are) and it did not handle this, otherwise I would most likely not have written the post.

Or are you saying Prettier _does_ handle this with a line break before JSDoc comment blocks, and I must have just done something awfully wrong to miss that?

**Comment by brettz9** [comment]
I wouldn't expect this would have problems with Prettier if properly implemented. However, we had two issues (#1295 and #1296), so the rule turned out to just not be ready.

**Comment by lamuertepeluda** [comment]
> @lamuertepeluda I have not updated to test the new rule yet, but when I wrote these we were using Prettier (and still are) and it did not handle this, otherwise I would most likely not have written the post.
> 
> Or are you saying Prettier _does_ handle this with a line break before JSDoc comment blocks, and I must have just done something awfully wrong to miss that?

sorry I didn't mention that I am using prettier + https://www.npmjs.com/package/prettier-plugin-jsdoc in my previous post

**Comment by thernstig** [comment]
@lamuertepeluda I do not think this plugin here can take into account all other plugins that exist, such as ::1 which is not wildly used either. I think you need to disable the rule in either of those plugins.

I like that this was added as default by @brettz9 (albeit of course fixing the two above bugs would be nice).

**Comment by brettz9** [comment]
I have since removed the rule from the recommended rules until such time as we may fix the bugs. At such a time, I would like to move the rule back (as again, I don't think it should conflict with prettier since it should just be adding a line, and prettier shouldn't need to collapse lines around JSDoc--at least I've never seen that happen).

**Comment by lamuertepeluda** [comment]
> @lamuertepeluda I do not think this plugin here can take into account all other plugins that exist, such as https://www.npmjs.com/package/prettier-plugin-jsdoc which is not wildly used either. I think you need to disable the rule as you did.
> 
> I like that this was added as default by @brettz9 (albeit of course fixing the two above bugs would be nice).

Agreed but for backward compatibility I would have expected it to be off by default.

Anyways, thanks for your hard work on this plugin 🙌 and if anyone else is having such issues with prettier can just turn this rule off.

**Comment by brettz9** [comment]
> > @lamuertepeluda I do not think this plugin here can take into account all other plugins that exist, such as https://www.npmjs.com/package/prettier-plugin-jsdoc which is not wildly used either. I think you need to disable the rule as you did.
> > I like that this was added as default by @brettz9 (albeit of course fixing the two above bugs would be nice).
> 
> Agreed but for backward compatibility I would have expected it to be off by default.

It was released as part of a semantic major version, so breaking changes should be expected in such cases. But again, there were some issues with the rule, so disabling for now.
 
> Anyways, thanks for your hard work on this plugin 🙌 

Thank you.

> and if anyone else is having such issues with prettier can just turn this rule off.

Sure.
