### ISSUE TITLE
Exception with multiple config files

### ISSUE THREAD

**Issue by danielrentz** [gajus/eslint-plugin-jsdoc#1282]
## Expected behavior
Linting succeeds

## Actual behavior
```txt
Error: ENOENT: no such file or directory, open '.../my_project/test/package.json'
    at Object.open (node:internal/fs/sync:78:18)
    at Object.openSync (node:fs:565:17)
    at readFileSync (node:fs:445:35)
    at .../my_project/node_modules/eslint-plugin-jsdoc/src/getJsdocProcessorPlugin.js:18:3
```

## ESLint Config
We have a project with a sub directory containing an additional "eslint.config.js" for some reason.
```
my_project/
    package.json
    eslint.config.js
    test/
        eslint.config.js  
```
Linting in this directory (`cd test && eslint .`) worked with `eslint-plugin-jsdoc` v48.8.x but fails with `eslint-plugin-jsdoc` v48.9.2. Maybe caused by the "move processor to own file" changes in 48.9.1.

## Environment

- Node version: 20.x
- ESLint version 9.8.0
- `eslint-plugin-jsdoc` version: 48.9.2

**Comment by brettz9** [comment]
Please let us know if the new release addresses the issue (as it should). Thanks!

**Comment by danielrentz** [comment]
@brettz9  It works, thank you for the quick fix!
