### ISSUE TITLE
How to restore require-jsdoc behavior from ^46.8.2

### ISSUE THREAD

**Issue by krutoo** [gajus/eslint-plugin-jsdoc#1292]
Hi, today I upgraded `eslint-plugin-jsdoc` from `^46.8.2` to `^48.11.0`

I noticed that now `require-jsdoc` rule works differently.

Previously I used this config for `require-jsdoc`:

```js
{
  'require-jsdoc': [
    'error',
    {
      require: {
        ArrowFunctionExpression: true,
        ClassDeclaration: true,
        FunctionDeclaration: true,
        FunctionExpression: true,
        MethodDefinition: true,
      },
    },
  ]
};
```

In old version this code provides error:
```js
// Error: requires JSDoc (and its ok, i need it)
export const foo = () => {
  return 1;
};

export const bar = {
  // Error: requires JSDoc (and its ok, i need it)
  hello () {
    return 'hi'
  },

  // No error here (and its ok, i dont need it here)
  baz: () => {
    // Error: requires JSDoc (and its ok, i need it)
    const id = a => a;

    return id(2);
  },
};
```

But now all this arrow functions don't provides errors about JSDoc missing.

How can I restore behavior from version `^46.8.2`?

**Comment by brettz9** [comment]
This code provides 4 errors in the latest version (including above `baz`).

I think the issue may be that your config has changed. You are using `require-jsdoc`, and it should be `jsdoc/require-jsdoc`. ESLint has its own version of the function, but it was deprecated and removed in ESLint 9.

**Comment by krutoo** [comment]
@brettz9 Oh, its true, I mixed up `require-jsdoc` and `jsdoc/require-jsdoc`, sorry

Previously I used `plugin:jsdoc/recommended` and `require-jsdoc`

Now I remove `require-jsdoc` because its deprecated

Is it possible to make `jsdoc/require-jsdoc` works as `require-jsdoc`?

**Comment by brettz9** [comment]
Yes, `jsdoc/require-jsdoc` should work similar to `require-jsdoc`, just with more features. It inherited the same codebase and just expanded on it.

**Comment by krutoo** [comment]
@brettz9 Looks like `jsdoc/require-jsdoc` now provides error for arrow functions in properties of objects

```js
{
  // Error: Requires JSDoc (I don`t need it here)
  foo: () => 123,

  // Error: Requires JSDoc (But here is ok, i need it here)
  bar () {
    return 234;
  }
}
```

Can you suggest how to configure this rule for disable requiring JSDoc in such cases?

**Comment by brettz9** [comment]
You can add the following object option:

```js
        {
          contexts: [
            ':not(Property) > ArrowFunctionExpression',
          ],
          require: {
            ArrowFunctionExpression: false,
            ClassDeclaration: true,
            FunctionDeclaration: true,
            FunctionExpression: true,
            MethodDefinition: true,
          },
        }
```

**Comment by krutoo** [comment]
@brettz9 can you provide some docs about expressions in contexts option?

Looks like your example dont works as well (maybe i did something wrong):

![image](https://github.com/user-attachments/assets/3b6e3f7f-3fd9-483d-88f8-9f1a09cda2ae)


Also now I have some new places where JSDoc is required:

- in default values of destructured object argument:
```js
function MyReactComponent ({ 
  getName = data => data.name // Error: Missing JSDoc (but I dont need it here)
}) {
  // ...
}
```

- For arrow functions as arguments:
```js
[1,2,3].map(() => {}); // Error: Missing JSDoc (but I dont need it here) 
```

**Comment by brettz9** [comment]
> @brettz9 can you provide some docs about expressions in contexts option?

The advanced page of our docs covers this a little, but as mentioned in the docs, your best bet is probably just experimenting with https://astexplorer.net/
 
> Looks like your example dont works as well (maybe i did something wrong):
> 
> ![image](https://private-user-images.githubusercontent.com/13140130/355344180-3b6e3f7f-3fd9-483d-88f8-9f1a09cda2ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjgwNzIsIm5iZiI6MTcyMjkyNzc3MiwicGF0aCI6Ii8xMzE0MDEzMC8zNTUzNDQxODAtM2I2ZTNmN2YtM2ZkOS00ODNkLTg4ZjgtOWYxYTA5Y2RhMmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA3MDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYWIzZTliYjc4N2ZjOGY1NTNkNjNiM2FjZGUyYjVmZTU0NDg1ZjgyNTMzMDEzMDcxZDRkMjNiMDE4ZWZjYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0rNGRiy_lTKA35EgdAwnN8re1fvQw5YHpJZt-ZUqedc)

I can't see the full object to know exactly what you're working with.

> Also now I have some new places where JSDoc is required:
> 
> * in default values of destructured object argument:
> 
> ```js
> function MyReactComponent ({ 
>   getName = data => data.name // Error: Missing JSDoc (but I dont need it here)
> }) {
>   // ...
> }
> ```
> 
> * For arrow functions as arguments:
> 
> ```js
> [1,2,3].map(() => {}); // Error: Missing JSDoc (but I dont need it here) 
> ```

While you could exclude more types than `Property`, you might just want to whitelist the types of allowing parents. You can add additional `contexts` to do so. The following mimics how the rule probably worked when it was part of ESLint (i.e., without the `Property` parent).

```js
        {
          contexts: [
            'VariableDeclarator > ArrowFunctionExpression',
            'AssignmentExpression > ArrowFunctionExpression',
            'ExportDefaultDeclaration > ArrowFunctionExpression',
          ],
          require: {
            ArrowFunctionExpression: false,
            ClassDeclaration: true,
            FunctionDeclaration: true,
            FunctionExpression: true,
            MethodDefinition: true,
          },
        }
```

**Comment by krutoo** [comment]
> I can't see the full object to know exactly what you're working with.

@brettz9 You don`t need full object, the error is exactly on this line with arrow function as default value (If I understand what do you mean)

**Comment by brettz9** [comment]
Closing as the above should resolve, but feel free to comment further as needed.
