### ISSUE TITLE
Code example for eslint-plugin-jsdoc needs to be updated

### ISSUE THREAD

**Issue by redrogers** [gajus/eslint-plugin-jsdoc#1302]
In the example config for eslintrc:

`plugins: [
   "jsdoc"
 ]`

needs to be updated to:
`plugins: [
    "eslint-plugin-jsdoc
 ]`

**Comment by brettz9** [comment]
As per https://eslint.org/docs/latest/use/configure/plugins-deprecated#configure-plugins

> The eslint-plugin- prefix can be omitted from the plugin name

So the docs should be all right as they are.

The ESLint 9/Flat Config format is altogether different, but that is documented separately:

```js
import jsdoc from 'eslint-plugin-jsdoc';

export default [
  {
    plugins: {
      jsdoc
  }
];
```

**Comment by brettz9** [comment]
Closing as I think it is ok, but feel free to comment further as needed.
