### ISSUE TITLE
require-jsdoc fails on classes with static block

### ISSUE THREAD

**Issue by patricklx** [gajus/eslint-plugin-jsdoc#1312]
## Expected behavior
report missing jsdoc on classes that also have static blocks

## Actual behavior
fails with a type error
```
TypeError: Cannot read properties of undefined (reading 'name')
Occurred while linting /.../test.js:1
Rule: "jsdoc/require-jsdoc"
    at getSymbol (.../node_modules/.pnpm/eslint-plugin-jsdoc@50.2.2_eslint@8.57.0_supports-color@9.4.0__supports-color@9.4.0/node_modules/eslint-plugin-jsdoc/dist/exportParser.cjs:194:125)
```

The code could probably be enhanced to handle unknown types so that new things that come up can be handled

## ESLint Config

```js
module.exports = {
  root: true,
  parser: '@babel/eslint-parser',
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    requireConfigFile: false,
    babelOptions: {
      root: __dirname,
    },
  },
  plugins: ['jsdoc'],
  extends: [
    'plugin:jsdoc/recommended',
  ],
  rules: {
    'jsdoc/require-description': 'warn',
    'jsdoc/require-jsdoc': ["error", {"publicOnly":true,"require":{"ClassDeclaration":true}}],
  },
}
```

## ESLint sample

```js
class Abc {
    static {
        this.x = '2'
    }
}
```

## Environment

- Node version: v18.17.1
- ESLint version 8.57.0
- `eslint-plugin-jsdoc` version: 50.2.2

**Comment by brettz9** [comment]
Thanks for the report. Fixed by #1313 .

With AST, there can be changes that break our assumptions, and it is not always easy to anticipate what these will be (or if it is, it can be cumbersome to handle every path). Feel free to report if these come up again, and we can hopefully give quick turnaround.
