### ISSUE TITLE
Readme documentation needs organizing

### ISSUE THREAD

**Issue by ibbignerd** [gajus/eslint-plugin-jsdoc#132]
When I was first looking at this package, I thought the whole documentation was in the root [README](https://github.com/gajus/eslint-plugin-jsdoc/blob/master/README.md). It wasn't until later that I saw the .README directory. After looking through that documentation, it seems that the root README doesn't have all of the updates. This was the [commit](https://github.com/gajus/eslint-plugin-jsdoc/commit/1b69b04237dd5a9c0b59f0f51d6975014124001b#diff-880ab63b2f5e3febc4f15d303ab3e426) I noticed. There might be more diffs, I just haven't looked though them yet.

I would be more than happy to update the documentation for it to be more organized. I just wanted to get feedback on how it should be structured. Here is my plan:

**/README.md**

This should contain the overview for the whole project and links to all of the rules (other documentation). We should also list Installation, Configuration, and Settings here. All of the rules should be removed and listed in their own files.

side note: Is there any benefit in linking to jscs-jsdoc anymore? It has pretty much gone full circle after it has been merged into eslint and now the jsdoc rules are being deprecated. 

**/.README/** should be renamed to **/docs/**. That's pretty standard.

**/docs/**

`/docs/` contains two directories: rules and settings. Each of the rules and setting should have their own md file. These should also include their examples. 

The examples also should be updated to look more like [eslint](https://eslint.org/docs/rules/no-multi-spaces#disallow-multiple-spaces-no-multi-spaces). I know it is a bit more weird weird with the rules and settings being a bit disjointed, but the rules are either on or off. You don't have to list every single setting to show how it interacts with each rule. Just show examples of how the rule affects the check and how the setting interprets the jsdoc. 

-----
## example-setting

Explain why the setting exists. 

```js
// Quick example showing the setting in action
```

### Rule Details

Explain what the setting checks

Examples of **incorrect** code for this setting:
```js
// a few examples showing incorrect code with default params
```

Examples of **correct** code for this setting:
```js
// a few examples showing correct code with default params
```

### Options

List the option names, their possible values, their default value, and a description.

#### exampleOption1

List examples of incorrect and correct code for each of the options. The option which disables the setting only needs the correct code example. Options that take in arbitrary values like `tagNamePreference` should show how to use it and the breaking options after they are changed. (using @param when you changed it to @arg)

---

Again, I'm willing to put forth the effort on this one. I just need to make sure the work will be well received. 

Thanks for reading!

**Comment by gajus** [comment]
Sorry, missed this issue originally.

The `.README` is not an alternative documentation. It contains the templates used to generate `README` with https://github.com/gajus/gitdown.

Happy to discuss the structure of ESLint rule description and accept a PR if the changes make sense.
