### ISSUE TITLE
Add check-examples usage examples

### ISSUE THREAD

**Issue by gajus** [gajus/eslint-plugin-jsdoc#139]
check-examples usage examples have been removed because the use of ``` is breaking the README.md markdown, see https://github.com/gajus/eslint-plugin-jsdoc/commit/dc5e015477a04d69f31d07ca09b3978d190d49ed.

**Comment by MuhamadOmr** [comment]
hey @gajus this is my first pull request to open source
glad i could help here #140

kindly review , if there any changes
