### ISSUE TITLE
Feature Request: Add valid-jsdoc's requireReturn Equivalent

### ISSUE THREAD

**Issue by niedzielski** [gajus/eslint-plugin-jsdoc#14]
The `valid-jsdoc` rule offers the [requireReturn](http://eslint.org/docs/rules/valid-jsdoc#requirereturn) option to flag missing `@returns`. If eslint-plugin-jsdoc offered something like `require-returns`, it could [replace](https://github.com/gajus/eslint-plugin-jsdoc/issues/1#issuecomment-182400324) all `valid-jsdoc` usage. This feature request is to track adding `require-returns` functionality. Thanks!

**Comment by gajus** [comment]
PR welcome.

**Comment by ptkdev** [comment]
Available in v3.15.0, need close this issue @gajus
