### ISSUE TITLE
You shouldn't need to specify @return if your function does an early return

### ISSUE THREAD

**Issue by ThosRTanner** [gajus/eslint-plugin-jsdoc#149]
e.g. I have some code like

/** function does this */
function fred()
{
    if (something) { return; }
    rest_of_stuff();
}

The plugin complains I don't document the return. eslint validate-jsdoc is happy with this if you specify requireReturn: false

**Comment by gajus** [comment]
https://github.com/gajus/eslint-plugin-jsdoc/issues/142
