### ISSUE TITLE
Allow passing additional valid tags to check-tag-name as an option

### ISSUE THREAD

**Issue by atakiel** [gajus/eslint-plugin-jsdoc#15]
As jsdoc allows defining custom tags via plugins, it should be possible to give additional valid tag names to 'check-tag-name' rule as options.

Additionally, with such an option, users wouldn't have to wait for this plugin to be updated in order to be able to use tags added in a new version of jsdoc.

**Comment by gajus** [comment]
I am Okay with this. Please raise a PR.

**Comment by jensbodal** [comment]
Any chance you can take another look at the pull request which addresses this? 

https://github.com/gajus/eslint-plugin-jsdoc/pull/23
