### ISSUE TITLE
require-returns-check don't detect implicit return

### ISSUE THREAD

**Issue by gabmontes** [gajus/eslint-plugin-jsdoc#156]
![image](https://user-images.githubusercontent.com/2621975/51990505-ebfe3080-2487-11e9-82bf-d4f59765e683.png)

The implicit return does not seem to be found by `require-returns-check` and the rule fails when it should not.

Using version 4.1.0.

**Comment by gajus** [comment]
Related https://github.com/gajus/eslint-plugin-jsdoc/issues/148

CC @james2doyle
