### ISSUE TITLE
support require-jsdoc

### ISSUE THREAD

**Issue by philsch** [gajus/eslint-plugin-jsdoc#161]
Just needed to search through the Issues section to find out that `require-jsdoc` is supported. It sounds trivial, but can you just add this information / example into the README? Thanks.

**Comment by gajus** [comment]
What is `require-jsdoc`?

It is not supported.

**Comment by philsch** [comment]
Sorry just noticed my mistake, I got it wrong from another conversation and just wanted to edit my request, but you responded too fast ;)

Am I right that there is no check possible at the moment for missing docblocks (as described in the deprecated package https://eslint.org/docs/rules/require-jsdoc). Can we turn this issue in a feature request?

Sorry again for not proper researching on my side.

**Comment by gajus** [comment]
Please raise as a new issue describing the requirement.

**Comment by allthesignals** [comment]
@philsch have you found a way to enforce requiring a JSDoc block? 

I believe the ask here is that the linter can identify undocumented classes, functions, methods, and so on. What more information is needed to clarify?

**Comment by philsch** [comment]
This issue was closed and re-created as #162 because this request was not formulated correctly in the first place (it is basically a duplicate). You are right, #188 and #205 resolve my request 👍
