### ISSUE TITLE
`check‑types`: Allow lower‑case `object`

### ISSUE THREAD

**Issue by ExE-Boss** [gajus/eslint-plugin-jsdoc#164]
TypeScript recommends `object` over `Object`, which&nbsp;is enforced by&nbsp;my&nbsp;ESLint config for&nbsp;the&nbsp;deprecated `valid‑jsdoc` rule, and would require changes to&nbsp;a&nbsp;lot&nbsp;of&nbsp;my&nbsp;code.

**Comment by brettz9** [comment]
If the `preferType` option from `valid-jsdoc` is carried over from ESLint (#107), one could define this rule for oneself (unless you *also* wanted to change the current behavior of `check-types`).

**Comment by brettz9** [comment]
Closed by #247. See https://github.com/gajus/eslint-plugin-jsdoc/tree/master/.README#settings-to-configure-check-types-and-no-undefined-types for use with `check-types`.

You can get this behavior now (in `master`) by:

```js
{
  settings: {
    jsdoc: {
      preferredTypes: {
        'Object': 'object'
     }
  }
}
```

However, I've asked @gajus if we might change the default, as I agree it makes more sense given that objects made with `Object.create(null)` are not `instanceof Object` and as mentioned, Typescript recommends "object".

**Comment by gajus** [comment]
> However, I've asked @gajus if we might change the default, as I agree it makes more sense given that objects made with Object.create(null) are not instanceof Object and as mentioned, Typescript recommends "object".

Go for it.

When merging, the commit message must include "BREAKING CHANGE:" and a description of the breaking change. This will cause new major version release. See https://github.com/semantic-release/semantic-release#commit-message-format

**Comment by dietergeerts** [comment]
So because TS is using `object`, the default is now `object`? What happened to the reasoning behind having it `Object` in the first place? I liked the reasoning because it made sense towards the JS language....

**Comment by brettz9** [comment]
Yes, in part because of TS which has become very popular. But there was a case missed by the original logic. Objects made with `Object.create(null)` are not `instanceof Object`. So if accepting an arbitrary object, it indeed may not be an instance of `Object`.

**Comment by dietergeerts** [comment]
Who would ever do that? I mean yes, technically it's possible, but why?

**Comment by brettz9** [comment]
Using `Object.create(null)` allows you to create objects which aren't at risk for inheriting from `Object.prototype` and for which `for...in` guards are not needed.

So if some code library adds this to a project you or your users are using:

```js
/**
* @example
* ({a: 1, b: 2}).getKeys()
*/
Object.prototype.getKeys = () => {
    return 'Object ' + Object.keys(this).join(', ');
};
```

...your code can do this:

```js
const map = Object.create(null);
map.someKey = 5;
for (const key in map) {
  console.log(key); // Logs `someKey` but not `getKeys`
}
```

whereas this will show the inherited `getKeys` as well:

```js
const map = {};
map.someKey = 5;
for (const key in map) {
  console.log(key); // Logs `getKeys` as well as `someKey`
}
```

**Comment by dietergeerts** [comment]
Thx for the explanation, that makes it all clear.

This shows what we know as 'prototype pollution', and must be banned Imho. No library should ever need to do this. That's why FP is way better in this regard.

I also think that this method of creating objects is not well known, and one could ask if it should be needed.

**Comment by brettz9** [comment]
Yes, extending the prototype is generally not a good practice, though it is useful for allowing polyfills. It can make for an attractive API, but I agree the cost isn't worth it.
