### ISSUE TITLE
`check‑tag‑names`: Support @template

### ISSUE THREAD

**Issue by ExE-Boss** [gajus/eslint-plugin-jsdoc#165]
The `@template` tag is&nbsp;used by&nbsp;the&nbsp;Closure compiler and&nbsp;TypeScript [for&nbsp;generics](https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript#template):
```js
/**
 * @template T
 * @param {T} x
 * @return {T}
 */
function identity(x) {
	return x;
}
```
is&nbsp;equivalent&nbsp;to:
```ts
function identity<T>(x: T) {
	return x;
}
```

**Comment by ibbignerd** [comment]
Resolved? @gajus

**Comment by ExE-Boss** [comment]
It’s not resolved yet, since https://github.com/gajus/eslint-plugin-jsdoc/pull/168 is still open.
