### ISSUE TITLE
[bug] TypeScript "Parameter properties" unsupported

### ISSUE THREAD

**Issue by rasenplanscher** [gajus/eslint-plugin-jsdoc#177]
Linting this file:
```
export class SomeClass {
    /**
     * @param property
     */
    constructor(private property: string) {}
}
```

`eslint` aborts with this Error:
> Error: Unsupported function signature format.

The stack trace points to at `eslint-plugin-jsdoc\dist\jsdocUtils.js:36:11`

Versions used:
+  eslint: 5.15.3
+  eslint-plugin-jsdoc: 4.4.3

For the feature's docs, see https://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties

**Comment by gajus** [comment]
Should be an easy enhancement given that ESLint can read that signature, it is just does not have a defined behaviour for it. PR welcome.

**Comment by rasenplanscher** [comment]
Done 😎👍
