### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ibbignerd** [gajus/eslint-plugin-jsdoc#180]
It would be a lot easier for someone to contribute if there was a document that explained some basic aspects of the project. 

1. How to test changes locally (npm link)
1. How to build the project
1. Coding standards
1. Are tests needed? If so, how to write them.
1. Requirements for PR

Of course, most of these can just be links to other resources, like `npm link`. The point of this document would allow someone who knows javascript, but doesn't necessarily know this project, how to contribute. 

This document is not a guide of how to write rules for eslint.

**Comment by ExE-Boss** [comment]
It should be called `CONTRIBUTING.md`

**Comment by brettz9** [comment]
Adding a tentative `CONTRIBUTING.md` file for #180.

Welcome your feedback!

**Comment by brettz9** [comment]
Fixed by #239.
