### ISSUE TITLE
Support ESLint 3 and new rule format

### ISSUE THREAD

**Issue by paazmaya** [gajus/eslint-plugin-jsdoc#19]
The new rule format, introduced in the ESLint version 3, is explained here http://eslint.org/blog/2016/07/eslint-new-rule-format

Any chance of converting the rules in that format and making a new major release which support ESLint 3 and up?

**Comment by gajus** [comment]
> Any chance of converting the rules in that format and making a new major release which support ESLint 3 and up?

It is an open-source project. Contributions are most welcome.

**Comment by ntwb** [comment]
> Contributions are most welcome.

I'd also like to see some ESLint 3 compatibility but I'm hesitant to even take a look as the pull request I created here ~5 months ago sits open with no feedback /shrug
