### ISSUE TITLE
Require JSDoc on exported methods

### ISSUE THREAD

**Issue by Extersky** [gajus/eslint-plugin-jsdoc#192]
Support rule that requires JSDoc comment on publicly exported functions. This was originally proposed for now deprecated ESLint rule https://eslint.org/docs/rules/require-jsdoc.

Original enhancement suggestion:
https://github.com/eslint/eslint/issues/7812

The rule could support ES6 exports and possibly other interfaces such as CommonJS exports.

**Comment by Extersky** [comment]
I have an ongoing implementation of this here: https://github.com/Extersky/eslint-plugin-jsdoc/commit/55fa30bfb4d3ef2eb744096bae3abc5f00113131

This version supports ES6 exports and CommonJS exports. Should CommonJS be supported for inclusion in this plugin? In the original proposal, only the ES6 exports were planned to be supported.

**Comment by ericrini** [comment]
+1

**Comment by brettz9** [comment]
Sounds quite useful, @Extersky . Could you prepare a PR?

I'd think config to choose between which type of modules were supported would be ideal, but even if it is automatically for both, I think it would be a very handy to have.

Regarding, always/public/never, @ericrini , this is more or less what is requested by #78 (though to selectively exclude private functions, thereby effectively enabling a public option in addition to the default "always" behavior).
