### ISSUE TITLE
Rule 'require-param' does not respect @inheritdoc

### ISSUE THREAD

**Issue by jscharett** [gajus/eslint-plugin-jsdoc#20]
According to the docs, the presence of @inheritdoc will cause jsdocs to ignore any other tags.  Since we are pulling in the docs from another node, then we should not have to re-declare the tags here as well.  This rule should check for the presence of the @inheritdoc and skip if found.  Same may also be true for @override, but I think that intended to work slightly different

**Comment by gajus** [comment]
@jscharett That sounds like a simple change. Can you look into raising a PR?

**Comment by freaktechnik** [comment]
Yes, @override sadly also triggers require-param.

**Comment by rsimha** [comment]
@freaktechnik this is likely to be fixed in #74.
