### ISSUE TITLE
Add documentation for the requireJSDoc rule

### ISSUE THREAD

**Issue by allthesignals** [gajus/eslint-plugin-jsdoc#208]
There needs to be documentation added for this new rule, `requirejsdoc`.

> Noticed after merging that this was submitted without the accompanying documentation. That would be a nice follow up PR.

_Originally posted by @gajus in https://github.com/gajus/eslint-plugin-jsdoc/pull/205#issuecomment-484580624_

**Comment by allthesignals** [comment]
In spite of passing tests, this feature isn't where it needs to be, and so can't fully be documented. Currently, it does not seem possible to override these defaults: 
https://github.com/gajus/eslint-plugin-jsdoc/blob/master/src/rules/requireJsdoc.js#L8-L27

At a bare minimum, you can enable this rule by adding the following to your `rules` object:
`"jsdoc/require-jsdoc": 1`

This will enforce `FunctionDeclaration`, but not the others, and I cannot find a way to override these defaults (hence my inability to write full documentation). 

It seems like additional changes to `iterateJsdoc.js` are needed for the linter to correctly pick up the ["options"](https://github.com/gajus/eslint-plugin-jsdoc/blob/master/test/rules/assertions/requireJsdoc.js#L41-L46) seen in the unit tests.

More broadly, I think this happened because of a lack of testing for https://github.com/gajus/eslint-plugin-jsdoc/blob/master/src/iterateJsdoc.js, or lack of inclusion of this step into the test suite, either of which would probably help with coverage.

I can take a longer look after this week!

**Comment by brettz9** [comment]
The options seem to be working for me, including outside of the tests... I'm picking up `{require: {ClassDeclaration: true}}` for example.

**Comment by brettz9** [comment]
I've added some docs for `require-jsdoc`.
