### ISSUE TITLE
Error while running ESLint: Failed to load plugin jsdoc

### ISSUE THREAD

**Issue by fonziemedia** [gajus/eslint-plugin-jsdoc#226]
Hi,

I've tried to setup the jsdoc plugin for eslint but I'm getting the following error:
"Error while running ESLint: Failed to load plugin jsdoc: Cannot find module 'eslint-plugin-jsdoc'."

I've got the following packages installed:
    "eslint": "^5.13.0",
    "eslint-plugin-jsdoc": "^4.8.4",

my .eslintrc is as follows:

`{
  "parser": "babel-eslint",
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended"
  ],
  "plugins": [
    "jsdoc"
  ],
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "rules": {
    "jsdoc/check-alignment": 1,
    "jsdoc/check-examples": 1,
    "jsdoc/check-indentation": 1,
    "jsdoc/check-param-names": 1,
    "jsdoc/check-syntax": 1,
    "jsdoc/check-tag-names": 1,
    "jsdoc/check-types": 1,
    "jsdoc/newline-after-description": 1,
    "jsdoc/no-undefined-types": 1,
    "jsdoc/require-description": 1,
    "jsdoc/require-description-complete-sentence": 1,
    "jsdoc/require-example": 1,
    "jsdoc/require-hyphen-before-param-description": 1,
    "jsdoc/require-param": 1,
    "jsdoc/require-param-description": 1,
    "jsdoc/require-param-name": 1,
    "jsdoc/require-param-type": 1,
    "jsdoc/require-returns": 1,
    "jsdoc/require-returns-check": 1,
    "jsdoc/require-returns-description": 1,
    "jsdoc/require-returns-type": 1,
    "jsdoc/valid-types": 1
  }
}`

Any help would be appreciated, thanks!

**Comment by brettz9** [comment]
Just to be sure--did you remember to run `npm install`?

**Comment by fonziemedia** [comment]
Thanks for the reply @brettz9 

You were right my issue was with npm. For some reason running 'npm install eslint-plugin-jsdoc' wasn't installing the package even thought it seemed so. I had to clear my npm cache, delete all modules and do an npm install from scratch.

The plugin seems to load correctly now but I don't get any jsdoc errors/warnings popping using eslint atom package. Might be an issue with the atom package though or maybe conflicts with other plugins (eslint-plugin-react?).

**Comment by brettz9** [comment]
Did you restart Atom after your install? Atom+ESLint doesn't seem to pick up changes to installs until a restart, apparently as it does its caching at startup...

**Comment by cwingrav** [comment]
Having the same issues. I removed both ESLint and eslint-plugin-jsdoc from global. Forced an npm cache clear. I can't get rid of this error:

```
Definition for rule 'jsdoc/check-alignment' was not found (jsdoc/check-alignment)
```

Other checks on jsdoc seem to work properly. Using this inside vim.

**Comment by brettz9** [comment]
up to date versions of eslint? what is your config and what triggers it for you? Can you provide a minimal config and file to reproduce?

**Comment by brettz9** [comment]
For anyone having this issue, please file a new issue with the config that triggers it. We can't reproduce if we don't have similar conditions--thank you! Be sure to also have the latest versions of eslint and eslint-plugin-jsdoc...

**Comment by fonziemedia** [comment]
Just a quick update: this is working for me now.

I was testing this incorrectly with a random jsdoc comment block but comments need to be right before functions for the linter to trigger which makes sense.

Thanks for the support!
