### ISSUE TITLE
The type "object" is undefined

### ISSUE THREAD

**Issue by goulderb** [gajus/eslint-plugin-jsdoc#249]
The changes in PR#248 seem to have caused some unintended side-effects.

If I have a JSDoc comment, like the one below, and I run eslint --fix, the uppercase "Object" type gets replaced with lowercase "object", however, this winds up triggering the jsdoc/no-undefined-types rule as "object" is not one of the matching types that is always considered defined:

Example, before eslint --fix:
```javascript
/**
 * Example
 *
 * @param {Object} obj An object parameter.
 * @returns {Object} An object
 */
const example = obj => obj;
```

Example, after eslint --fix:
```javascript
/**
 * Example
 *
 * @param {object} obj An object parameter.
 * @returns {object} An object
 */
const example = obj => obj;
```

**Comment by brettz9** [comment]
Thanks for the report!
