### ISSUE TITLE
do not use non-public 'eslint/lib/util/ast-utils'

### ISSUE THREAD

**Issue by aladdin-add** [gajus/eslint-plugin-jsdoc#251]
I'm from eslint, and was trying to use the plugin in elsint codebase, but got an error:
![image](https://user-images.githubusercontent.com/13050025/58248610-2bca8a00-7d8f-11e9-9a1a-fe168413b923.png)

seems the plugin was using a non-public API "eslint/lib/util/ast-utils", which is not recommended. as we may change it in any release.

**Comment by gajus** [comment]
> seems the plugin was using a non-public API "eslint/lib/util/ast-utils", which is not recommended. as we may change it in any release.

What is the equivalent?

**Comment by aladdin-add** [comment]
the new file is "lib/rules/utils/ast-utils.js". please note it's available in eslint@>6.0.0-alpha.1, and not published yet.

**Comment by golopot** [comment]
I copy-pasted the function used.

**Comment by brettz9** [comment]
IMO, would be nice to have a devDep and `cp` script in `package.json` to pull in/try out fresh updates more easily...

**Comment by brettz9** [comment]
Just looked at the function--didn't know it was that simple :-) No worries then...
