### ISSUE TITLE
Ensure setting and option defaults are documented

### ISSUE THREAD

**Issue by brettz9** [gajus/eslint-plugin-jsdoc#256]
Some defaults are not documented.

- [x] Review options
- [x] Review settings

**Comment by brettz9** [comment]
I think I can finish this issue up in the process of moving `check-examples` to options. All other settings (as with options) now have defaults documented, except with maps like `tagNamePreference` which should really imply that they only apply to the items in the maps.

I note though that two settings are not indicated in the rule tables, `ignorePrivate`--which applies to all rules, and `tagNamePreference` which applies to many returns/param functions (this one is mentioned in one rule for which its role is more significant, `check-tag-names`). Do we want all the potentially applicable settings mentioned across all rule tables, or only if the settings particularly apply to a given rule?

**Comment by brettz9** [comment]
@golopot, any thoughts about this?

**Comment by golopot** [comment]
I have not thoughts about this :octopus:.
