### ISSUE TITLE
require-returns-check doesn't work with generator functions

### ISSUE THREAD

**Issue by leomeloxp** [gajus/eslint-plugin-jsdoc#271]
When trying to write a generator function (`*myfunction`) `require-returns-check` complains that no return statement is found even though the function contains the `yield` keyword (which essentially works as a return.

Example code (using Typescript): 

```ts
    /**
     * Generator for prizes:
     * @returns {IterableIterator<number>}
     * @memberof GameController
     */
    public *prizes(): IterableIterator<number> {
        for (const prizeValue of this.prizes) {
            yield prizeValue;
        }
    }
```

I searched through existing issues and found that there were some issues with the checker and implicit returns before. I believe this would be a similar kind of issue, if someone gives me some tips I could try and PR a fix for it.

**Comment by brettz9** [comment]
It has been enhanced considerably, but that would be a nice addition. However, I think we'd want to distinguish (maybe toggled with an option) cases where `yield`'s were of the form `let receivedValue = yield;` (without a returned value) and whether these would be considered as returning a value or not.

**Comment by brettz9** [comment]
I've found https://astexplorer.net/ quite helpful in getting around the AST...

**Comment by brettz9** [comment]
Btw, while [`@yields`](https://jsdoc.app/tags-yields.html) is [not currently supported in TypeScript](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc), I think for jsdoc users, it would make more sense to check that tag instead.

**Comment by brettz9** [comment]
Closing in favor of #354 . For TypeScript at least, #354 should also allow the `IterableIterator` `@returns` as as well as `@yields`
