### ISSUE TITLE
Exempt certain methods from `require-jsdoc`

### ISSUE THREAD

**Issue by lozog** [gajus/eslint-plugin-jsdoc#272]
Is it possible to exempt certain methods from `require-jsdoc`? For example, when using a framework like React, a JSDoc doesn't add anything useful on lifecycle methods.

**Comment by HsuTing** [comment]
I found a solution:

```js
module.exports = {
  settings: {
    jsdoc: {
      additionalTagNames: {
        customTags: ['react']
      },
    },
  },
  rules: {
    'jsdoc/require-example': ['error', { exemptedBy: ['react'] }], 
    'jsdoc/require-param': ['error', { exemptedBy: ['react'] }], 
  },
};
```

In my component:
```js
class Example extends React.PureComponent {
  /** @react */
  componentDidMount() { ... }

  /** @react */
  render() { ... }
}
```

By this way, we can ignore the jsdoc in `react life cycle`.
If we can use the more better way to do this, let me know, please.

**Comment by brettz9** [comment]
I think an ideal solution would be to add an `exemptedContexts` option. Then the user could add AST like `MethodDefinition[key.name='componentDidMount']` to an array where the rule would not be enforced.

This could then be implemented by adding a `:not()` query to the end of the rule selector (e.g., in places where the boolean `contextDefaults` is currently applied; we might also expand `exemptedBy` (which would probably be better named to `exemptedTags`) to these other rules as well).

**Comment by brettz9** [comment]
I realized we can actually already exclude `require-jsdoc` by using negated `contexts`.

```js
{
  contexts: ['MethodDefinition:not([key.name="componentDidMount"]):not([key.name="render"])']
}
```

Don't include `{MethodDefinition: true}` on the `require` options object  though as the above will replace that.

I've added the above example to the [docs](43c9d8303b3c105e1f005ed82c0aa6abc51d7e90).

See also the new section on ["AST and Selectors"](https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-advanced-ast-and-selectors) toward gaining a better understanding of how the AST for a language feature can be determined.

**Comment by nfantone** [comment]
For anyone looking to exclude `jsdoc/require-jsdoc` from functional components, you can use:

```json
  "rules": {
    "jsdoc/require-jsdoc": [
      "warn",
      {
        "require": {
          "ArrowFunctionExpression": false,
          "FunctionDeclaration": false
        },
        "contexts": [
          "FunctionDeclaration:has(BlockStatement > ReturnStatement:not([argument.type='JSXElement']))",
          "ArrowFunctionExpression:has(BlockStatement > ReturnStatement:not([argument.type='JSXElement']))"
        ]
      }
    ]
  }
```

**Comment by FTWinston** [comment]
Many thanks for the above! I came up with the following to disable the require-param rule for function components, whether declared as functions or arrow functions:

```js
"rules": {
  "jsdoc/require-param": [
    "warn",
    {
      "contexts": [
        "FunctionDeclaration:not([id.name=/^[A-Z].+/])",
        "VariableDeclarator:not([id.name=/^[A-Z].+/]) > ArrowFunctionExpression"
      ]
    }
  ]
},
``
