### ISSUE TITLE
require-example only on class declaration

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [gajus/eslint-plugin-jsdoc#273]
Hello!

I would like to know if there is a way to enforce examples only on (es6) ClassDeclaration ?

Thanks in advance,
Benjamin Van Ryseghem

**Comment by brettz9** [comment]
It currently only requires examples on functions with no way to even enable for classes (`check-examples`, however, currently looks at both classes and functions, but with no way to configure).

I'm thinking we should support an option--and add it to a number of rules--which allows one to specify the AST types one wishes to support (such as `ClassDeclaration`).

**Comment by BenjaminVanRyseghem** [comment]
Thanks for the quick answer!
