### ISSUE TITLE
Shouldn't this be a dev dependency?

### ISSUE THREAD

**Issue by cowwoc** [gajus/eslint-plugin-jsdoc#274]
ESLint recommends installing their library as a dev dependency. You install it using `npm install eslint --save-dev`.

Why does the README of this library recommend installing it as a non-dev dependency?

> `npm install eslint-plugin-jsdoc`

**Comment by brettz9** [comment]
While I guess it is just being non-committal about whether you wish to save it or not (it is not explicitly saving it to production (with `--save` or `-P`), and if one is installing globally, I wouldn't imagine it makes any difference, but if one is saving it, indeed it should be saved to dev, so I would tend to agree that it would be more clear to indicate saving both `eslint` and `eslint-plugin-jsdoc` to dev.

@gajus  ?

**Comment by gajus** [comment]
It should be `--save-dev`.
