### ISSUE TITLE
Allow "any" to rules with `contexts`

### ISSUE THREAD

**Issue by brettz9** [gajus/eslint-plugin-jsdoc#325]
For rules with a `contexts` option (`match-description`, `require-example`, `require-description`, and `require-jsdoc`), though one may not wish these applied to all contexts, there are nevertheless cases for doing so, particularly for the first, and less so for the second, but even potentially for the others.

I'd like to see us allow an "any" option or allowing `contexts` to be set to `true` to indicate all contexts.

*Update*: In my PR, I decided against adding for `require-jsdoc`, as it would require separate refactoring, and probably not worth the effort for that particular rule.

**Comment by golopot** [comment]
Setting context to "all" means that `require-example` will apply to file-level jsdoc, ESNext class fields, and variable declarations. I don't think people will want that.

As for `match-description`, it seems that it should be applied to all jsdoc comments.

**Comment by brettz9** [comment]
Yes, I agree `require-example` is unlikely at that level, but since we're using the same code for it, I don't think it'd hurt to allow it, as with `require-jsdoc` for which it would be similarly unlikely. But definitely an option for `require-description`.

And as we previously discussed, I do think there ought to remain separate levels of control for `match-description` because it is styling that one might not care to enforce outside of certain contexts like functions. `match-description` already allows `contexts`, so I'd like `match-description` to accept any.

**Comment by golopot** [comment]
That sounds reasonable, I am good with this.
