### ISSUE TITLE
require-description-complete-sentence not working with @typedef

### ISSUE THREAD

**Issue by krutoo** [gajus/eslint-plugin-jsdoc#333]
![image](https://user-images.githubusercontent.com/13140130/61126245-674b2000-a4c5-11e9-9387-1d94b2db7f7e.png)

Hello, i noticed that the rule does not work with the tag "typedef".

`eslint-plugin-jsdoc: 8.5.1`

Please help me fix the problem.

**Comment by golopot** [comment]
Confirmed this is still a bug in in `15.3.5`.
