### ISSUE TITLE
JSDoc/GCC/TypeScript mode

### ISSUE THREAD

**Issue by brettz9** [gajus/eslint-plugin-jsdoc#356]
#354 proposes adding a `mode` setting for allowing different behavior between TypeScript, Closure, and regular jsdoc. This setting could be used for other tweaks:

- [x] Avoid `parseClosureTemplateTag` in `no-undefined-types` except for `closure`
- [x] Toggle `check-syntax` behavior (report non-GCC when in closure mode)
- [x] Start checking `module` for namepaths (see "todo" in `jsdocUtils.js` source), but only for "jsdoc" (and "closure"?) mode (TS doesn't support)
- [x] `valid-types`
    - [x] `valid-types` - Ensure tags with optional type (`tagsWithOptionalTypePosition`) only allow for `package`, `private`, `protected`, `public`, and `static` if in closure mode.
    - [x] `valid-types` - Only allow `@extends {SomeType}` with brackets if in closure mode.
    - [x] `valid-types` - Only allow `@typedef {SomeType}` (without a name) in closure mode.
    - [x] Report name on [`@interface`](https://jsdoc.app/tags-interface.html) in Closure
- [x] Don't check optional name on [`@interface`](https://jsdoc.app/tags-interface.html) in Closure
- [x] For `check-tag-names`, avoid allowing `@template` except in `closure` and `typescript`
- [x] For `check-tag-names`, add other GCC tags for `closure` mode (#306)
- [x] `check-tag-names` to prefer other defaults with `tagNamePreference` (`return` over `returns`)
- [x] See about getting jsdoctypeparser (e.g., see https://github.com/jsdoctypeparser/jsdoctypeparser/issues/50 on TypeScript support) to support different modes so long as jsdoc/TypeScript/Closure differ in the formats supported (might have comments which are used to build alternate versions of the peg file, e.g., stripping out those for TypeScript or Closure only). One explicitly desired rule to be avoided for closure per #495 is to disallow tuples. Might also have a tolerant version (the default?) which accepted all forms though (?).

Might accept a version in an array along with the mode string in case jsdoc, Closure, or TypeScript make breaking changes or add more features.

**Comment by l1bbcsg** [comment]
`check-syntax` is another important rule to tweak. Currently it tweaks agains GCC style, but in gcc mode it could have the opposite behavior.

`check-types ` rule, `preferredTypes` and `tagNamePreference` settings could use different defaults in GCC mode, i.e. prefer `return` over `returns`.

**Comment by brettz9** [comment]
Thanks, @l1bbcsg , I've amended the original post to include `check-syntax`, but I mentioned `check-tag-names` instead of `check-types` in relation to `tagNamePreference`; do you have an example of a type that differs from gcc if `check-types` also should toggle behavior?

**Comment by l1bbcsg** [comment]
One case I can think of is that `Function` and `function` both could be used in GCC code and have different meaning.

Technically, `Boolean` and `boolean` are also different types, but I can't think of any real-world scenario where you could find a difference.

You can look into GCC types in details here: [Types in the Closure Type System
](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System)

**Comment by brettz9** [comment]
Both `Function` and `function` could be used in regular jsdoc as well, though in regular jsdoc, there is no `function()` (with parentheses). The fact that regular jsdoc should not handle `function()` type syntax is reflected already in the to-do for getting `jsdoctypeparser` to support different modes and setting such a mode.

Re: real world differences between `Boolean` and `boolean`, `typeof` treats them differently: `typeof new Boolean(true) === 'object'` vs. `typeof true === 'boolean'`. The rule `check-types`  prefers `boolean` since use of Object-wrapped primitives is generally frowned upon. I don't see that this should differ between regular jsdoc and GCC.

**Comment by ExE-Boss** [comment]
Actually, [`@template` is valid when in TypeScript mode](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#template).

**Comment by brettz9** [comment]
Ah, good catch, thanks @ExE-Boss !

**Comment by brettz9** [comment]
> `check-syntax` is another important rule to tweak. Currently it tweaks agains GCC style, but in gcc mode it could have the opposite behavior.

We can switch `check-syntax` to stop preventing `=` for "closure" (and a hopefully soon to be introduced "permissive" mode).

However:
1. JSDoc explicitly supports Closure syntax
2. Does Closure fail to handle the jsdoc style of enclosing optional names in brackets? If so, I can see requiring it, but otherwise I'm not so sure.

I think `check-syntax` should be limited to checking syntax which is discouraged, less popular, or not available in a given mode. But if there are equally viable options, and projects may differ in which to enforce, I think we should let another rule handle it or add an option to override preventing certain features. We don't want the rule to have some features that people want but an inability to turn them off.

So if Closure does support optional names in brackets, I don't think it should be prevented by this rule even for "closure" mode. However, since jsdoc/typescript has what I think may be the more popular option of enclosing names in brackets, I can see continuing to forbid the Closure style for this rule (though we could make this optional at a future point if the rule came to handle other syntax and people wanted to allow it).

Are there any other syntax features you want prevented in Closure mode only?

**Comment by brettz9** [comment]
Oh, and with #586, combined with a PR to jsdoctypeparser to prevent `=` except in "closure" and "permissive" modes, this rule's currently sole feature might become obsolete, since `valid-types` could easily be made (with such a change in jsdoctypeparser) to no longer accept the optional `=` for "jsdoc" and "typescript" modes (the jsdoctypeparser source also mentions other similar optional types as "deprecated").

**Comment by brettz9** [comment]
While I've gone ahead and stopped `check-types` from reporting Closure optional types when in "closure" mode, an option could be added to force it to be allowed. Other mode-specific changes are also welcome as separate issues, but the initial checklist here is now complete, so is being closed.
