### ISSUE TITLE
[Feature Request] Spell-checking

### ISSUE THREAD

**Issue by AndrewLeedham** [gajus/eslint-plugin-jsdoc#359]
This has perhaps come up before, I had a quick search through the Issues and couldn't find anything. But would it be in scope to add a spell check rule for `@param`, `@returns`, title, description etc? Maybe using a library such as https://www.npmjs.com/package/simple-spellchecker

**Comment by gajus** [comment]
Seems more like a job for your IDE in general. Feels like such a rule would add more noise than good.

**Comment by AndrewLeedham** [comment]
I agree it would make sense coming from the IDE. The use-case I am more thinking of is PR reviews, meaning I would not have to scrutinise spelling when reading through large commits, I can just skim over JSDoc comments making sure they make logical sense for what the function is doing rather than if it is spelled correctly.

**Comment by gajus** [comment]
https://www.npmjs.com/package/eslint-plugin-spellcheck

**Comment by AndrewLeedham** [comment]
> https://www.npmjs.com/package/eslint-plugin-spellcheck

Yeah I came across that, but it doesn't look like it is maintained anymore.

**Comment by gajus** [comment]
It has been last updated 14 days ago.

Either way, this really doesn't belong in this plugin.

**Comment by AndrewLeedham** [comment]
Yeah issues seem dry though, either way if it is our of scope here, that is fine 😃 Thanks.
