### ISSUE TITLE
Support for ESLint 4.0.0

### ISSUE THREAD

**Issue by kunagpal** [gajus/eslint-plugin-jsdoc#36]
With ESLint 4.0.0, the following error message shows up:
```
npm ERR! node v4.8.3
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package eslint@4.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-jsdoc@3.1.0 wants eslint@>=0.8.0
```

**Comment by gajus** [comment]
I don't see whats the problem, the peerDependency condition does allow v4

https://github.com/gajus/eslint-plugin-jsdoc/blob/d99da900a71a71ecec13a8bc65dc24cd4355b69d/package.json#L39

**Comment by kunagpal** [comment]
Yes, but the warning would not even show up in that case. 😓

**Comment by gajus** [comment]
You are using `v2.15.11`.

Thats more likely to be a bug in NPM than anything else.
