### ISSUE TITLE
 Expected JSDoc block to be aligned.  jsdoc/check-alignment

### ISSUE THREAD

**Issue by OmgImAlexis** [gajus/eslint-plugin-jsdoc#368]
The first returns a warning. The second is what was returned from `--fix`. The example I'm using is from the examples on [jsdoc/check-alignment](https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-check-alignment
).

```
  ⚠  8:0  Expected JSDoc block to be aligned.  jsdoc/check-alignment

  1 warning
```

```js
module.exports = function (si) {
	/**
      * Desc
      *
      * @param {number} foo
      */
     function quux(foo) {
     }
};

```
```js
module.exports = function(si) {
	/**
  * Desc
  *
  * @param {number} foo
  */
	function quux(foo) {
	}
};
```

**Comment by golopot** [comment]
Looks like the rule does not handle tab indents properly.

**Comment by brettz9** [comment]
Fixed by #412

Note, however, that the fix is based on the assumption that the initial line is the one with the correct indentation. So in your case, the fixed code will look like:

```js
module.exports = function (si) {
	/**
	 * Desc
	 *
	 * @param {number} foo
	 */
     function quux(foo) {
     }
};
```

If you wanted to see the indent instead made relative to the function or other context it is preceding, a new issue could be filed.

**Comment by OmgImAlexis** [comment]
@brettz9 a new issue would be a great idea. Would you mind opening it?

**Comment by brettz9** [comment]
I have filed #413 . In the future, please file yourself so you can be automatically subscribed to the issues and can state the concern as you see it.

To subscribe to that issue without needing to add any comments, you can click Github's "Subscribe" button on the page for #413 on the right-hand side of the page.

Thanks for the report!

**Comment by OmgImAlexis** [comment]
You don’t need to treat me like an idiot. I know how to use Github. I was on my phone when I saw the notification that’s all. 💁‍♀️

**Comment by brettz9** [comment]
I didn't know about the Subscribe button last year or so despite being on Github for years! But then again, I may be idiot, so I wouldn't know how to treat others otherwise. :)

**Comment by brettz9** [comment]
And FWIW, as a former teacher, I tend to overexplain things to *everyone* in the event not only that the immediate listener doesn't happen to know but also in case others coming across the issue don't either, so even if I do state something seemingly obvious, please don't take it as being directed at you.

**Comment by 646767173** [comment]
> 

you don't need to apologize, you are doing a right thing, my friend.
