### ISSUE TITLE
With TypeScript CTRL+S adds bad comments to a function inside a class.

### ISSUE THREAD

**Issue by jasson2788** [gajus/eslint-plugin-jsdoc#369]
Hey guys!

Inside a class and pressing CTRL+S will add to this code.
```
class Dog {
	eat() {
		
	}
}
```

A comment like that: 
```
class Dog {
    eat/**
 *
 */
() {
		
    }
}
```
Expected result:
```
class Dog {
    /**
     * 
     */
    eat() {
		
    }
}
```

P.S. I am using TypeScript.

Thank you guys.

**Comment by jasson2788** [comment]
Hello, @golopot.

I hope you are doing well. Any updates on that issue? The issue still happens when autofix is on.

**Comment by golopot** [comment]
Pull requests are welcomed.
