### ISSUE TITLE
Add option to set error level with "plugin:jsdoc/recommended"

### ISSUE THREAD

**Issue by RamzesTheSecond** [gajus/eslint-plugin-jsdoc#379]
I would like to use  "plugin:jsdoc/recommended" and be able to specify: 'off', 'warn', or 'error' for all those options with need to list them all.

E.g. 
`
"settings": {
    "jsdoc": {
      "errorLevel": "error" //or "warn" or "off"
    }
  }
`

**Comment by brettz9** [comment]
This is really something that I think makes more sense to be handled by eslint, though unforunately, imo, such issues as https://github.com/eslint/eslint/issues/10690 have been rejected.

However, you could make your config file a JavaScript file and dynamically create the error levels you want, possibly building configs or serving the file, if you can't use `process.argv` (e.g., if your IDE is running the eslint and is beyond your control).
