### ISSUE TITLE
Is there a way to lint access modifiers?

### ISSUE THREAD

**Issue by rafaelgssa** [gajus/eslint-plugin-jsdoc#380]
I want to use this:

```js
class MyClass {
  constructor() {
    /** @private */
    this.property = false;
  }
}
```

And have this display an error:

```js
new MyClass().property = true;
```

Is there a way to do this with this plugin?

**Comment by brettz9** [comment]
This strikes me as something more for the likes of TypeScript.

**Comment by brettz9** [comment]
Closing as there has been no other feedback, and I really think we're agreed that this kind of deep analysis belongs more in the likes of TypeScript.
