### ISSUE TITLE
Atom require-jsdoc

### ISSUE THREAD

**Issue by jssuttles** [gajus/eslint-plugin-jsdoc#386]
I'm not sure if this should be handled by this plugin, but when running Atom (with linter-eslint), the jsdoc/require-jsdoc rule causes the entire function to be highlighted.
When running intellij, it just highlights the first line of the function.
I would prefer that it not highlight the entire function.

**Comment by jssuttles** [comment]
Thanks for working on this! However, the problem doesn't seem to be fixed.
![image](https://user-images.githubusercontent.com/8527741/65776269-c822e580-e10f-11e9-9680-54a9b8e03c77.png)

**Comment by jssuttles** [comment]
Nvm. restarted atom and it worked.
Thanks!!!

**Comment by brettz9** [comment]
Did you restart Atom after updating? It caches the files...

**Comment by jssuttles** [comment]
Here's something I noticed though. It doesn't highlight the first line.
If possible, that would be nice to have since it causes the user to notice.
![image](https://user-images.githubusercontent.com/8527741/65777016-31efbf00-e111-11e9-8e8a-be4e9ec68783.png)

**Comment by brettz9** [comment]
You can try updating now to 15.9.5 (and restart Atom again after that).

**Comment by jssuttles** [comment]
That's pretty good. I'll take it. 👍 
Thanks!
