### ISSUE TITLE
`check-types`: Traversing variadic AST (for `function(...)`) gives "TypeError: Cannot read property 'type' of null"

### ISSUE THREAD

**Issue by vapier** [gajus/eslint-plugin-jsdoc#389]
code snippet:
```js
/** @param {function(...)} callback The function to invoke. */
var subscribe = function(callback) {};
```

eslint crashes:
```
TypeError: Cannot read property 'type' of null
Occurred while linting test.js:2
    at .../node_modules/eslint-plugin-jsdoc/dist/rules/checkTypes.js:133:25
    at opt_onEnter (.../node_modules/jsdoctypeparser/lib/traversing.js:19:7)
...
```

this basically means the func accepts an arbitrary number of arguments of arbitrary type.

* eslint-6.4.0
* eslint-15.9.5
* jsdoctypeparser-5.0.1

**Comment by brettz9** [comment]
This appears, in a sense, to be an issue with jsdoctypeparser. While we could wrap the `traverse` function in a try-catch, jsdoctypeparser shouldn't be passing the parsing stage and failing at the traverse stage.

So an issue should really be filed there.

However, I'm not sure what the course of action should be in this case. It is not entirely clear that the variadic format you are using--three dots not followed by anything--is considered acceptable or not (and if so by which jsdoc dialects).

- Closure does not make explicit mention of such a type: https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler ; though the jsdoctypeparser pegjs source points to a file for this format (perhaps in reference to [this line](https://github.com/google/closure-library/blob/47f9c92bb4c7de9a3d46f9921a427402910073fb/closure/goog/base.js#L1847)?), I'm not sure that this single example is authoritative--unless there is some code that processes variadic arguments which I did not find.
- I'm not sure about TypeScript; seems there is an issue filed to add support: https://github.com/microsoft/TypeScript/issues/5453
- vanilla jsdoc, whether at https://jsdoc.app/tags-type.html or https://jsdoc.app/tags-param.html do not make mention of such a type.
- JSDuck does not seem to support: https://github.com/senchalabs/jsduck/wiki/Type-Definitions

As a workaround (until determination is made on whether to eliminate this possibility or fully support it) you might use `...*` or `...any`.

**Comment by brettz9** [comment]
This is now blocking on https://github.com/jsdoctypeparser/jsdoctypeparser/issues/89 .

Feel free to subscribe there.
