### ISSUE TITLE
'require-param' completely broken now with latest eslint 4.7.1 release

### ISSUE THREAD

**Issue by harryi3t** [gajus/eslint-plugin-jsdoc#41]
![image](https://user-images.githubusercontent.com/5207331/30591273-ba0e0678-9d5f-11e7-9d5e-5efdbb404fff.png)

**Comment by digitalkaoz** [comment]
same here, our pipelines are broken all of a sudden -.-

**Comment by digitalkaoz** [comment]
@harryi3t did you solve it by downgrading one or another? eslint@4.7.0 doenst work...

**Comment by digitalkaoz** [comment]
found it, its https://github.com/yavorskiy/comment-parser  `0.4.1` that causes the problem, downgrading to 0.3 solved it here

**Comment by digitalkaoz** [comment]
@gajus can you create pinned version for `comment-parser@0.3.2`

**Comment by harryi3t** [comment]
@digitalkaoz I solved this by turning off the rule and adding a todo comment to fix it later 😄 
Hope this gets fixed soon

**Comment by SergeAstapov** [comment]
Issue is fixed for me as of v3.1.3

**Comment by harryi3t** [comment]
Thanks! It's working now.
