### ISSUE TITLE
Align to indent of succeeding function/context rather than to top of jsdoc block

### ISSUE THREAD

**Issue by brettz9** [gajus/eslint-plugin-jsdoc#413]
User @OmgImAlexis [requested](https://github.com/gajus/eslint-plugin-jsdoc/issues/368#issuecomment-547268423) that `check-alignment` be changed to have alignment based on the function or context that follows a comment, rather than the top of the jsdoc block.

For example:
```js
module.exports = function (si) {
	/**
      * Desc
      *
      * @param {number} foo
      */
     function quux(foo) {
     }
};
```

...should be fixed to:

```js
module.exports = function (si) {
    /**
     * Desc
     *
     * @param {number} foo
     */
     function quux(foo) {
     }
};
```

not to:

```js
module.exports = function (si) {
	/**
	 * Desc
	 *
	 * @param {number} foo
	 */
     function quux(foo) {
     }
};
```

**Comment by golopot** [comment]
I am not sure this is necessary. Rule `indent` indent the comment start, and `jsdoc/check-alignment` indent the comment body wrt the comment start, as a result the whole comment is indented properly.

Also doing this may ensue conflicts with the the rule `indent`. If there is no conflict, then the implementation is duplicating the work of `indent`.

**Comment by brettz9** [comment]
Ah, ok, with `indent` indeed appearing to check for comments (unless its [`ignoreComments`](https://eslint.org/docs/rules/indent#ignorecomments) option is enabled), I would therefore tend to agree that this is redundant, so will close, though @OmgImAlexis , feel free to comment further as needed.
