### ISSUE TITLE
Enable commitizen config in this repo

### ISSUE THREAD

**Issue by OmgImAlexis** [gajus/eslint-plugin-jsdoc#442]
Since this repo seems to use angular style commit messages may I suggest adding a [script called "commit"](https://github.com/commitizen/cz-cli#using-the-command-line-tool) which uses commitizen.

It'd allow new users to easily use the same commit message format as you're expecting. It can also be [integrated with husky](https://github.com/commitizen/cz-cli#husky) in the pre-commit stage.

**Comment by brettz9** [comment]
If added to husky, what would happen for GUI Git apps? Maybe we could have it only auto-apply after the message is attempted and it fails validation?

**Comment by brettz9** [comment]
@gajus : Are you open to my setting this up? It looks like it just adds a couple devDeps.

It looks like [commitlint](https://commitlint.js.org/#/guides-local-setup?id=test-the-hook) might also be helpful for those not using the interactive commitizen so as to ensure the message format is checked. (one can apparently do so on `prepush`, so one can rush a local commit with poorly formed messages until one is ready to revise them properly: https://github.com/conventional-changelog/commitlint/issues/361 ).

**Comment by brettz9** [comment]
@OmgImAlexis : If you still want this, can you maybe prepare a PR, including `commitlint` ideally, so we would just need to review?

**Comment by OmgImAlexis** [comment]
I can’t promise a timeframe but sure. 😊

**Comment by brettz9** [comment]
Closing as haven't heard back, but feel free to submit a PR if you wish.
