### ISSUE TITLE
Unsupported @fires/@emits: Syntax error in namepath (jsdoc/valid-types)

### ISSUE THREAD

**Issue by yvele** [gajus/eslint-plugin-jsdoc#453]
The tags `@fires` (and `@emits`) are not supported and writing an event using the official JSDoc syntax https://jsdoc.app/tags-fires.html make the `jsdoc/valid-types` to fail.

```
@fires <className>#[event:]<eventName>
```

```js
/**
 * Drink the milkshake.
 *
 * @fires Milkshake#drain
 */
Milkshake.prototype.drink = function() {
    // ...
};
```

Makes `jsdoc/valid-types` to throw

> Syntax error in namepath: #drain      jsdoc/valid-types

PS: Is there a workaround for this?

**Comment by brettz9** [comment]
I'm not able to replicate this as a problem. What version of `jsdoctypeparser` is in your project (in `node_modules`). You can see it by `npm list --depth=0 jsdoctypeparser`.

And what version of `eslint-plugin-jsdoc`?

**Comment by yvele** [comment]
- `eslint-plugin-jsdoc` v18.4.3
- `jsdoctypeparser` v6.1.0

**Comment by brettz9** [comment]
I can't see how you'd be getting this unless you omitted "Milkshake", i.e., `@fires #drain`.

If that is not the case, I think we'd need a minimal test repo to debug this, as I'm not able to replicate in our testing environment.

**Comment by yvele** [comment]
My bad... I think I made an error somewhere and omitted "Milkshake" i.e. `@fires #drain`

Sorry 😉
