### ISSUE TITLE
`jsdoc/check-types` preferences should be and fixable

### ISSUE THREAD

**Issue by ProLoser** [gajus/eslint-plugin-jsdoc#46]
For the (preference) rules about `{function}` => `{Function}` and `{Boolean}` => `{boolean}`.

I would also like to see common mistakes fixed too: `{int}` or `{integer}` or `{float}` => `{number}`

**Comment by gajus** [comment]
There are valid use cases for `Function` and `Boolean`, etc. This would be a potentially destructive fix.

**Comment by ProLoser** [comment]
Then it doesn't make sense why there are rules that flag this if they are valid usecases. Make it configurable if you want the rules but not the fix (which seems contradictory to me)

**Comment by gajus** [comment]
These cases are extremely rare. If your intention is to use `{Function}`, then either ignore that specific line or disable the rule.
