### ISSUE TITLE
How to allow both return/returns for check-tag-names

### ISSUE THREAD

**Issue by deep9** [gajus/eslint-plugin-jsdoc#488]
Hi I struggle with setting the check-tag-names rule. I would like to have all the values checked, but allow both return and returns to be used.

Is there a way how to achieve this?

Thanks.

**Comment by deep9** [comment]
Thanks to @polomsky solution was found, but feels kind of hackish
```
const rules = {
    ...
    "settings": {
        "jsdoc": {
            "tagNamePreference": {
                "return": "return",
                "returns": "returns",
            }
        }
    },
    ...
};
```

**Comment by brettz9** [comment]
Yeah, there's been an assumption in the codebase that one form is to be preferred over another. Other rules may expect this as well, only checking, for example, the form preferred in `tagNamePreference`. IMO, avoiding this would not only allow projects that wanted it more flexibility but would simplify the code (though it would come with a (likely only minor) performance cost of checking potentially more than one tag variant for any given rule).
