### ISSUE TITLE
require-jsdoc for Typescript interfaces

### ISSUE THREAD

**Issue by andrewpurdin** [gajus/eslint-plugin-jsdoc#496]
I would like to require jsdoc comments on typescript interfaces, types, and enums. The `require-jsdoc` rule only seems to offer classes, methods, and functions as options. Is there an existing way to enforce comments on these, or is this a feature request?

**Comment by brettz9** [comment]
Add the AST types to the [`contexts`](https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-require-jsdoc) option to the rule.

You'll have to consult a list of TypeScript AST to find the types or use a `@typescript-eslint/parser`-supporting AST explorer like https://astexplorer.net/ (there is also https://ts-ast-viewer.com/ and that is TS-specific, but it is not using `@typescript-eslint/parser` which adapts TS interfaces into the AST needed by ESLint and which we are using).

So, for example:

```js
'jsdoc/require-jsdoc': ['error', {contexts: ['TSInterfaceDeclaration', 'TSTypeAliasDeclaration', 'TSEnumDeclaration']}]
```

Closing as that should address it, but feel free to comment further as needed.

**Comment by andrewpurdin** [comment]
Thanks for the explanation, that worked beautifully!
