### ISSUE TITLE
Add .jscsrc and/or .eslintrc files

### ISSUE THREAD

**Issue by skoblenick** [gajus/eslint-plugin-jsdoc#5]
Please add your .jscsrc and/or .eslintrc file(s) to the project; otherwise running the linters result in errors as my default config is different then yours. Unless your really have 57 Errors and 31 warnings when running `npm run lint` which your  travis-ci builds should because of if that is the case.

**Comment by gajus** [comment]
> Unless your really have 57 Errors and 31 warnings

That could have been the case.

Please see if you are getting these errors now.
