### ISSUE TITLE
add a knob to control opt_ prefixes

### ISSUE THREAD

**Issue by vapier** [gajus/eslint-plugin-jsdoc#509]
we want to stop people from using `opt_` prefixes  when a parameter is optional, but muscle memory can be hard, and sometimes we miss it during review.  could a config knob be added to require/disallow/ignore `opt_` prefixes on parameters relative to its optional setting ?

for example, we have code that does:
```js
/**
 * Internal helper for resyncing internal state.
 *
 * Used when the mappings change.
 *
 * @param {!Object=} opt_glmap Additional mappings to overlay on top of the
 *     base mapping.
 */
function foo(opt_glmap) {
```

since the `@param` has an `=` on it, we don't want the `opt_` prefix as it's redundant.

**Comment by brettz9** [comment]
Though #483 is in the context of spaces/tabs, the discussion there kind of ties in to this, as we could have regexes which match against the name portion (though such a rule would also need to specify contexts and tags--like `match-description`).

**Comment by brettz9** [comment]
If there were a `match-name` rule which simply prevented `opt_`, would that meet your needs? Is this practice used in any big projects like Closure that you know? Or is this just your local convention? I'm afraid that if unless it is just a rule to match names, it seems a bit project-specific.

**Comment by vapier** [comment]
a knob to run a regex across all variable names would suffice

the "don't use `opt_`" rule comes from the Google JS style guide:
https://google.github.io/styleguide/jsguide.html#features-functions-parameter-return-types

i won't make claims for how widely that guide is adopted outside of Google and Google-maintained projects, but it does seem to be in the top hits when searching for the topic, and referenced in articles discussing JS style guides.

**Comment by brettz9** [comment]
Here's a new test case for the `jsdoc/no-restricted-syntax` rule which now will let you at least get reporting for (though not fixing of) `opt_` prefixes:

```js
{
      code: `
        /**
         * @param opt_a
         * @param opt_b
         */
        function a () {}
      `,
      errors: [{
        line: 2,
        message: 'Only allowing names not matching `/^opt_/i`.',
      }],
      options: [{
        contexts: [
          {
            comment: 'JsdocBlock:has(JsdocTag[name=/opt_/])',
            context: 'any',
            message: 'Only allowing names not matching `/^opt_/i`.',
          },
        ],
      }],
    },
```
