### ISSUE TITLE
[require-jsdoc] Require JSDoc only either for the getter or the setter

### ISSUE THREAD

**Issue by manuth** [gajus/eslint-plugin-jsdoc#515]
People might want to add a comment for a getter/setter pair only once rather than writing two comments:
```js
class TestClass {
    constructor() {
        this.id = 1;
    }

    /**
     * Gets or sets the ID.
     */
    get ID() {
        return this.id;
    }

    set ID(value) {
        this.id = value;
    }
}
```
instead of this:
```js
class TestClass {
    constructor() {
        this.id = 1;
    }

    /**
     * Gets or sets the ID.
     */
    get ID() {
        return this.id;
    }

    /**
     * @inheritdoc
     */
    set ID(value) {
        this.id = value;
    }
}
```

**Comment by brettz9** [comment]
If you always put your `get` and `set` in that order, you could use the sibling selector, e.g., in this example excluding docs on a getter or setter followed by a setter or getter respectively (or on a constructor):

```js
{
          contexts: [
            'MethodDefinition:not([kind="constructor"],[kind="get"],[kind="set"])',
            'MethodDefinition[kind="get"]:not(MethodDefinition[kind="set"] + MethodDefinition[kind="get"])',
            'MethodDefinition[kind="set"]:not(MethodDefinition[kind="get"] + MethodDefinition[kind="set"])',
          ]
```

However, this does not take into account method name, so for example, while this would as desired, only require docs on the first block:

```js
          get ID() {
              return this.id;
          }

          set ID(value) {
              this.id = value;
          }
```

...so too would this:

```js
          get something() {
              return this.id;
          }

          set ID(value) {
              this.id = value;
          }
```

**Comment by ocket8888** [comment]
I think having only a `get` is much more common than only a `set`, so at a minimum I think even just having an option like `"checkSetters": "no-getter"` to only check `set`s when there's no `get` by the same name would be a great improvement.
