### ISSUE TITLE
Way to lint typos in param types?

### ISSUE THREAD

**Issue by pdehaan** [gajus/eslint-plugin-jsdoc#52]
I have a few code bases which have JSDoc comments with typos, similar to the following:

```js
 * @param  {Orbject} weightedVariations Weight of a variant.
```

Is there any way to check that a param's type is valid, and not some clumsy typo like "Orbject" or "stirng"?

**Comment by tdmalone** [comment]
What about https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-check-types?

**Comment by pdehaan** [comment]
@tdmalone I wasn't able to get "jsdoc/check-types" to catch my clumsy typo errors:

```js
// index.js
/**
 * What a useless method...
 * @param  {string}  a First string.
 * @param  {String}  b Second string.
 * @param  {srtring} c Third string.
 * @return {HelloWorld}    Concatenated string.
 */
function func1(a, b, c) {
  return a + b + c;
}

module.exports = func1;
```

```js
// .eslintrc.js
module.exports = {
  env: {
    es6: true,
    node: true
  },

  plugins: [
    'jsdoc'
  ],

  root: true,

  rules: {
    'jsdoc/check-types': 'error'
  }
};
```

```json
{
  "name": "jsdoc-testr",
  "version": "1.0.0",
  "author": "Peter deHaan",
  "devDependencies": {
    "eslint": "4.13.1",
    "eslint-plugin-jsdoc": "3.3.0"
  },
  "scripts": {
    "test": "eslint ."
  }
}
```

Now, running `$ npm test` triggers ESLint and gives me the following output:

```sh
$ npm test

> jsdoc-testr@1.0.0 test /Users/pdehaan/dev/tmp/del/jsdoc-testr
> eslint .

/Users/pdehaan/dev/tmp/del/jsdoc-testr/index.js
  1:1  error  Invalid JSDoc @param "b" type "String"  jsdoc/check-types

✖ 1 problem (1 error, 0 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.

npm ERR! Test failed.  See above for more details.
```

So if I understand correctly, `jsdoc/check-types` is only checking the native object types against a list of valid values, and therefore it catches my "string" vs "String" error. But it isn't catching my `{srtring}` typo, or wildly random `{HelloWorld}` data type.

**Comment by tdmalone** [comment]
I do apologise - I misunderstood the intent of check-types!

**Comment by pdehaan** [comment]
> I do apologise - I misunderstood the intent of check-types!

Me too! I had to do a lot of digging and reading of source code to try and figure out what was going on and why it wasn't doing what I naively expected. I was hoping there was an option or other rule for strict data type validation so it'd only recognize native data types, and force me to explicitly specify other data types.

PS: This plugin rocks! A huge thanks to everybody involved for working on it!

**Comment by brettz9** [comment]
You can use `no-undefined-types`. However, to add awareness of the existence of your `HelloWorld` type, you'd either need to define it in the document, add it within `/* globals */`, or give us a PR for #99. :)

**Comment by brettz9** [comment]
I therefore think this issue can be closed.
