### ISSUE TITLE
Add fixers to a few rules

### ISSUE THREAD

**Issue by bary12** [gajus/eslint-plugin-jsdoc#53]
The following rules can be automatically fixed with `eslint --fix`, when fixers are added.

* checktypes
* newline-after-description
* require-description-complete-sentence
* require-hyphen-before-param-description

My project just started using ESlint, doing require-description-complete-sentence manually is a pain so we don't use it for now.

If I have free time I might open a pull request for at least some of these. @gajus what do you think?

**Comment by bary12** [comment]
See [this commit](https://github.com/bary12/eslint-plugin-jsdoc/commit/cd6f9edfecab49cf28af5626a9377e5800b637d8) on my fork.

**Comment by gajus** [comment]
PR welcome.

**Comment by bary12** [comment]
pull request #54 was merged.
