### ISSUE TITLE
CI tests should include 6.0.0 / 7.0.0 as well as 6.x/7.x

### ISSUE THREAD

**Issue by edg2s** [gajus/eslint-plugin-jsdoc#538]
peerDependencies lists these as the minimum requirements for the 6.x/7.x branches, so we should probably test them, in case we end up inadvertently using a feature that was fixed in a minor release.

**Comment by brettz9** [comment]
@golopot / @gajus : Any opinions? I can see the desire for this, though OTOH, there could be regressions at some point in the middle too and we wouldn't be checking for those. And we already have a fair number of checks with two ESLint versions and the various Node versions. Another option would be bumping the peerDeps. I see `eslint-plugin-unicorn` has already dropped ESLint 6 support, for example. One doesn't wish to unduly break things, but one also doesn't want false reporting of support (and bug reports based on this).

**Comment by brettz9** [comment]
I think I will close this for the reasons stated. The matrix can already add overhead to testing time. Thanks!
