### ISSUE TITLE
Question about class documentation.

### ISSUE THREAD

**Issue by andrei9669** [gajus/eslint-plugin-jsdoc#546]
I'm using Webstorm for development and since 2020 update, there is this new feature that shows JSDoc when hovering over a class/function. 
Problem is tho, currently, if I use these rules
`
{
"rules": {
    "jsdoc/require-jsdoc": [
      "warn",
      {
        "require": {
          "ArrowFunctionExpression": true,
          "ClassExpression": true,
          "FunctionExpression": true,
          "MethodDefinition": true
        }
      }
    ],
    "jsdoc/require-description": 1,
    "jsdoc/require-description-complete-sentence": 1
  },
  "settings": { "jsdoc": { "preferredTypes": { "*": false } } }
}
`
ESLint forces me to add description and params to constructor, but Webstorm doesn't show class params if they are on constructor, but it shows, when they are on class itself.
![image](https://user-images.githubusercontent.com/31692094/82303819-2153c800-99c4-11ea-8bb4-7a306e7b1c53.png)
![image](https://user-images.githubusercontent.com/31692094/82303903-40525a00-99c4-11ea-97bb-23e7a8648bc4.png)

Can I somehow configure rules so that it would require to write the class definition and constructor props on top of the class.

Also, one more thing, is it possible to somehow not require jsdoc on top of extended functions, for example in ReactJs lifecycle functions.

**Comment by brettz9** [comment]
Please look at the README for `require-jsdoc` for how to require for a class--noting that there are different `require` needed depending on the type of class (a class expression or class declaration). `contexts` may also be used to set up particular conditions. See the examples.

Your other question on excluding the constructor is also addressed there in an example as well. Search through the examples with "constructor" and you will see one with a `contexts` which excludes constructor `MethodDefinition`'s.

**Comment by brettz9** [comment]
See #272 for your lifecycle question--to which I hope to post something there shortly.

**Comment by brettz9** [comment]
Re: excluding the lifecycle methods, see my comment just now at https://github.com/gajus/eslint-plugin-jsdoc/issues/272#issuecomment-630760995 .
