### ISSUE TITLE
Multiplicated auto fixes for jsdoc/require-param

### ISSUE THREAD

**Issue by Morikko** [gajus/eslint-plugin-jsdoc#547]
## Expected behavior
```js
function add(a, b,c) {
  return a + b + c;
}
```
Save -> autofix with VScode
```js
/**
 *
 */
function add(a, b, c) {
  return a + b + c;
}
```
Save -> autofix with VScode
```js
/**
 * @param a
 * @param b
 * @param c
 */
function add(a, b, c) {
  return a + b + c;
}
```

## Actual behavior
```js
function add(a, b,c) {
  return a + b + c;
}
```
Save -> autofix with VScode
```js
/**
 *
 */
function add(a, b, c) {
  return a + b + c;
}
```
Save -> autofix with VScode
```js
/**
 * @param a
 * @param b
 * @param c
 * @param a
 * @param b
 * @param c
 * @param a
 * @param b
 * @param c
 */
function add(a, b, c) {
  return a + b + c;
}
```
--> It writes the params as many times as there are params in the function (here 3 times and so on)

## ESLint Config
```json
{
  "parserOptions": {
    "ecmaVersion": 2018
  },
  "env": {
    "browser": false,
    "node": true,
    "es6": true
  },
  "plugins": ["jsdoc"],
  "settings": {
    "jsdoc": {
      "mode": "typescript"
    }
  },
  "rules": {},
  "extends": ["eslint:recommended", "plugin:jsdoc/recommended"]
}
```

## ESLint sample

```js
function add(a, b,c) {
  return a + b + c;
}
```

## Environment

* Node version: 10.19.0
* ESLint version: 6.8.0
* `eslint-plugin-jsdoc` version: 25.4.2

**Comment by brettz9** [comment]
When I run `eslint` through the command line, even multiple times, I don't get this result.

Using the auto-fix in Atom's `linter-eslint` similarly does not give me any problem.

It seems this is an issue that should perhaps be reported to VSCode.

I'm afraid the only other thing I can think of is to restart the IDE in case you had upgraded and there was a bug in the version you had previously.

I'm going to close, as I don't see anything further we can do. But feel free to comment further as needed.
