### ISSUE TITLE
New rule: `newline-between-tags`

### ISSUE THREAD

**Issue by hbergren** [gajus/eslint-plugin-jsdoc#552]
## Motivation

In all of our repos, there is an inconsistency between different functions and how they handle whitespace, especially between `@param` and `@returns`. For example:

```
/**
 * ...
 *
 * @param var - ...
 * @returns ...
 */
```

vs

```
/**
 * ...
 *
 * @param var - ...
 *
 * @returns ...
 */
```

Ideally I would like to be able to enforce consistency here.

## Current behavior

No opinion about lines between JSDoc members.

## Desired behavior

Enforce an opinion about lines between JSDoc members.

## Alternatives considered

Not aware of any alternatives except a new rule.

**Comment by brettz9** [comment]
We have `newline-after-description` for the newline between the main description and other tags, and the other aspects sounds like a dupe of #93.

**Comment by hbergren** [comment]
@brettz9 , sorry for not noticing the existing issue. I'll close this in favor of #93
