### ISSUE TITLE
Option to support or ban hyphens before other tag descriptions

### ISSUE THREAD

**Issue by hbergren** [gajus/eslint-plugin-jsdoc#553]
## Motivation

We use the [require-hyphen-before-param-description](https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-require-hyphen-before-param-description) rule, and in some cases, people get confused and add hyphens for other JSDoc tags. The most common one I see is adding a hyphen to the `@returns` tag.

## Current behavior

No way to discourage writing something like:
```
/**
 * ...
 * @returns - description
 */
```

## Desired behavior

Have some way to discourage using hyphens for JSDoc tags that are not `@param`.

## Alternatives considered

I tried using the `match-description` and setting a regex, but it seemed to ignore the presence/absence of a hyphen.

**Comment by brettz9** [comment]
Since `require-hyphen-before-param-description` already has the logic and despite its name can check `@property` too, how about we add an array option (e.g., `tags`) to it whose items would be objects with keys such as perhaps `tagName` and `circumstance: "always|never"`. We could potentially allow `any` as well so that the main options would apply to all tags.

**Comment by hbergren** [comment]
That sounds reasonable to me!

**Comment by hbergren** [comment]
@brettz9 , are there any rules you can point me to as an example that have an array of tag objects?

I took a quick look at the [require-hyphen-before-param-description source](https://github.com/gajus/eslint-plugin-jsdoc/blob/master/src/rules/requireHyphenBeforeParamDescription.js), but it's non-obvious to me how to refactor this to loop through an array of `tags` that may or may not have `circumstance === always`

**Comment by brettz9** [comment]
I've submitted PR #555 which simplifies from my proposal to use an array of `tagName` + `circumstance` objects to instead just use a single `tags` object with tag names as keys and circumstances as values.

**Comment by brettz9** [comment]
And `*` as a key for the "any" situation.

**Comment by hbergren** [comment]
#555 looks great! Thanks for implementing this!
