### ISSUE TITLE
TypeError: ancestorNodes.flatMap is not a function

### ISSUE THREAD

**Issue by deraw** [gajus/eslint-plugin-jsdoc#560]
## Expected behavior

Runs without error like in v27.0.0

## Actual behavior

The following error is occuring: `ERROR  TypeError: ancestorNodes.flatMap is not a function`

The error occurs on this line https://github.com/gajus/eslint-plugin-jsdoc/blob/master/src/rules/noUndefinedTypes.js#L80

## ESLint Config

```js
module.exports = {
	parser: 'vue-eslint-parser',
	extends: [
		'plugin:vue/recommended',
		'eslint:recommended',
		'@vue/typescript/recommended',
		'plugin:jsdoc/recommended'
	],
	rules: {
		'jsdoc/require-param': 0,
		'jsdoc/require-returns': 0
	},
	parserOptions: {
		parser: '@typescript-eslint/parser'
	},
	plugins: [
		'jsdoc'
	]
};
```
I pasted a simplified version of the config used were I encounter the bug but I think it will occur even without the Vue.js configuration

## ESLint sample

This seems to occur in any place

```ts
/** v-debounce directive */
export const debounce: DirectiveOptions = {};
```

## Environment

* Node version:  10.20.1
* ESLint version: 6.8.0
* `eslint-plugin-jsdoc` version: 27.0.1

**Comment by brettz9** [comment]
Ugh, had forgotten `flatMap` isn't supported on older Node. Fixed.

To prevent this in the future, @gajus, I think `eslint-plugin-compat` would have caught such a case if you were open to adding it.

**Comment by deraw** [comment]
@brettz9 Thank you for fixing this issue so quickly! 😃
