### ISSUE TITLE
New rule: `require-throws`

### ISSUE THREAD

**Issue by hbergren** [gajus/eslint-plugin-jsdoc#566]
## Motivation

The same way we have `require-returns` and `require-param`, I think there would be value in a `require-throws` rule.

## Current behavior

Currently, given a function that has a `throw` keyword, that throws an Error, I have no way to require documenting that the function throws an error using ESLint.

## Desired behavior

If a function contains the `throw` keyword, require having a `@throws` in the JSDoc for the function.

**Comment by brettz9** [comment]
Wouldn't catch all cases naturally, but would still be of good value. This might be a good first issue as one could follow the `require-returns` rule.

**Comment by brettz9** [comment]
Closed by #574 . Thanks again!
