### ISSUE TITLE
Place auto-generated JSDoc comments above decorators/annotations

### ISSUE THREAD

**Issue by seanblonien** [gajus/eslint-plugin-jsdoc#571]
## Motivation

Place JSDoc in the proper location relative to decorators/annotations.

TypeScript projects frequently use decorators for classes and functions and the autofix for `jsdoc/require-jsdoc` places JSDoc in the wrong place.

## Current behavior

Currently, the eslint fixer for the rule `jsdoc/require-jsdoc` places an auto-generated JSDoc in between the declaration/definition and decorator instead above the decorator like so:

```typescript
@Entity('users')
/**
 *
 */
export class User {}
```
See the live example [here](https://repl.it/@sblonien/eslint-jsdoc-requiredoc-autofix-issue#user.entity.ts).

## Desired behavior

The fixer should place the auto-generated JSDoc above the decorator like so by default:

```typescript
/**
 *
 */
@Entity('users')
export class User {}
```

Decorators are part of the definition/declaration so that's why comments should go above them.

## Alternatives considered

Location of a JSDoc relative to a decorator could be made into a setting that either places the JSDoc above or below decorators.

**Comment by david-sharer** [comment]
I am still seeing issues with this in the case of multiple annotations.  
Version 30.7.8

It considers this valid:
```ts
@Injectable({
  providedIn: 'root',
})
@State<Partial<UserSettingsStateModel>>
({
  name: 'userSettings',
  defaults: {
    isDev: !environment.production,
  },
})
/** Defines the current user's settings. */
export class UserSettingsState { }
```

When run with --fix and no documentation, it attempts to place the doc comment line so:
```ts
@Injectable({
  providedIn: 'root',
})
@State<Partial<UserSettingsStateModel>>
/**
 *
 */
({
  name: 'userSettings',
  defaults: {
    isDev: !environment.production,
  },
})
export class UserSettingsState { }
```

It considers this "missing" (though VS Code picks it up fine)
```ts
/** Defines the current user's settings. */
@Injectable({
  providedIn: 'root',
})
@State<Partial<UserSettingsStateModel>>
({
  name: 'userSettings',
  defaults: {
    isDev: !environment.production,
  },
})
export class UserSettingsState { }
```

**Comment by brettz9** [comment]
@david-sharer : No guarantees of being able to get to it, but please feel a new report so it is not lost.
