### ISSUE TITLE
require-description-complete-sentence only checks for @returns and not for @return

### ISSUE THREAD

**Issue by bm-stschneider** [gajus/eslint-plugin-jsdoc#60]
If you have also https://eslint.org/docs/rules/valid-jsdoc enabled to enforce consistency, this can collide with
https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-require-description-complete-sentence if you enforce the use of @return instead of @returns. Both is valid but it is not checked for the description ends with . rule.

**Comment by bary12** [comment]
There is already a pull request fixing this, #59 is waiting to be merged. @gajus

**Comment by bm-stschneider** [comment]
Thanks for the heads up.
