### ISSUE TITLE
publicOnly doesn't recognize classes xor methods

### ISSUE THREAD

**Issue by apowers313** [gajus/eslint-plugin-jsdoc#648]
Reposted from #288 

## Expected vs actual behavior
This flavor of exporting a class triggers `Missing JSDoc comment` on the `method` but not the `class`:
``` js
class Utility {
    mthd() {
        return false;
    }
}

module.exports = Utility;
```

This flavor of exporting a class triggers `Missing JSDoc comment` on the `class` but not the `method`:
``` js
module.exports = class Utility {
    mthd() {
        return false;
    }
};
```

## ESLint Config

``` js
"jsdoc/require-jsdoc": [
    "error", {
        enableFixer: false,
        publicOnly:  true,
        require:     {
            ClassDeclaration:        true,
            ClassExpression:         true,
            FunctionDeclaration:     true,
            FunctionExpression:      true,
            MethodDefinition:        true,
            ArrowFunctionExpression: true,
        },
    },
],
```

## Environment

- Node version: v14.8.0
- ESLint version v5.16.0
- `eslint-plugin-jsdoc` version: 30.6.3

**Comment by PsycheSloLo811** [comment]
![gmsnet2](https://user-images.githubusercontent.com/72146486/97946611-99cefb00-1d50-11eb-8652-00c87dc95127.jpg)

**Comment by PsycheSloLo811** [comment]
I have no idea what I am doing what do you think

**Comment by brettz9** [comment]
@PsycheSloLo811  : Your image isn't showing anything
