### ISSUE TITLE
require-description-complete-sentence tries to capitalize variable names in @return

### ISSUE THREAD

**Issue by cscott** [gajus/eslint-plugin-jsdoc#65]
For example:
```
 	 * @return {Object}
-	 *   @return {any} return.value
-	 *   @return {boolean} return.modified If the value of the attribute changed since we parsed the wikitext
-	 *   @return {boolean} return.fromsrc Whether we got the value from source-based roundtripping
+	 *   @return {any} Return.value.
+	 *   @return {boolean} Return.modified If the value of the attribute changed since we parsed the wikitext.
+	 *   @return {boolean} Return.fromsrc Whether we got the value from source-based roundtripping.
 	 */
```

**Comment by cscott** [comment]
It seems like this is a bit of a grey area in the jsdoc docs: https://github.com/jsdoc3/jsdoc3.github.com/issues/115

In any case, it is probably straightforward to make the code skip the first part of the string if the tag is `@return` and the string starts with `return.<identifier>`, and that ought to work fine whatever convention you are using.

**Comment by bary12** [comment]
It's not obvious as this code is already a mess. It should be done by adding a custom parser to comment-parser which excludes it from the description.

**Comment by brettz9** [comment]
This should also tie into #11

**Comment by brettz9** [comment]
At this point, I would hesitate to support this. As a style that is not formally documented at the very least, and is not supported in TypeScript JSDoc (and with our plan to move to TypeScript JSDoc by default)--which has an easier object shorthand syntax that can be used in its place, I don't think this is something even for "jsdoc" mode.

Closing, therefore, though feel free to comment further as needed.
