### ISSUE TITLE
Document whether rule is in recommended

### ISSUE THREAD

**Issue by kkmuffme** [gajus/eslint-plugin-jsdoc#652]
It would be really helpful, if the docs would state if a rule is in the "recommended" rule set or not.

Maybe as a separate line in this table, which exists for all rules:
![image](https://user-images.githubusercontent.com/11071985/97116627-b8a11200-16fe-11eb-967d-ee3465b182bd.png)

**Comment by brettz9** [comment]
The recommended status is currently listed in https://github.com/gajus/eslint-plugin-jsdoc#configuration . You mean you want to add mention of it inline with the rule info also?
