### ISSUE TITLE
Support Google Closure Compiler-style type expressions (JSDoc 3.2)

### ISSUE THREAD

**Issue by basickarl** [gajus/eslint-plugin-jsdoc#657]
I'm not sure if this should be put in https://github.com/gajus/eslint-plugin-jsdoc/issues/145 since that one specifically states TypeScript. Just tell me if it is!

According to the JSDoc 3.2 specification located here https://jsdoc.app/tags-type.html Google Closure Compiler-style type expressions should be supported.

## Motivation

People are using TypeScript more and more, there is more information about this type of syntax rather than the old Object.<string, number> syntax which there is less information about.

## Current behavior

Causes errors: `Syntax error in type: [string, Message][]eslintjsdoc/valid-types`

## Desired behavior

No errors.

**Comment by brettz9** [comment]
Your ESLint config either needs to use `parser: '@typescript-eslint/parser'` or have `settings.jsdoc.mode` set to 'typescript'.

**Comment by basickarl** [comment]
@brettz9 Ah that is indeed interesting. I'm curious, why is the mode referred to as "typescript" when it is stated in the JSDoc specification? JSDoc isn't coupled to TypeScript afaiac (I am aware that TypeScript uses (Google Closure Compiler-style type expressions, so it happens to work). Shouldn't the "mode" be referred to as "JSDoc-3.2"?

**Comment by brettz9** [comment]
Firstly, `Object.<string, number>` is not equivalent to `[string, Message][]`. The former (which is valid plain jsdoc) means an object with string keys and numeric values whereas the latter would mean an array of two-item arrays (with the first item in the tuple always being a string and the second item always being a `Message`). While the `[]` syntax for arrays is supported, such "tuples" (indicating types within array positions) are not supported in jsdoc per https://github.com/jsdoc/jsdoc/issues/1703 nor in Closure per https://github.com/google/closure-compiler/issues/379 . (Note that this "tuple" is different from the stage 2 JavaScript tuple proposal: https://github.com/tc39/proposal-record-tuple .)

**Comment by basickarl** [comment]
Thank you for taking the time to explain this! I've been with TypeScript for a few years but want to move over to JavaScript + JSDoc and this helped!
