### ISSUE TITLE
Support ignore-next-line inside JSDoc comment block

### ISSUE THREAD

**Issue by basickarl** [gajus/eslint-plugin-jsdoc#658]
I'm unsure if this issue belongs in this repo or if I should file it over at eslint since `eslint-disable-next-line` is an eslint thing. But then again you'd never need it to work inside a JSDoc block if you aren't using JSDoc.
```
/**
 * @param {Messages} messages Object containing the messages in chronological order.
 * eslint-disable-next-line jsdoc/no-undefined-value
 * @returns {processMessage} Function that will handle incoming messages.
 */
export function processMessageWrapper(messages) {
    /**
     * Processes incoming messages.
     *
     * @param {string} message Incoming message from stdin.
     */
    function processMessage(message) {
```

## Motivation

To disable rules for specific lines.

## Current behavior

Doesn't work, it's not possible to disable next lines in JSDoc comment blocks.

## Desired behavior

Would like to disable next line inside JSDoc comment block.

**Comment by brettz9** [comment]
As far as disabling lines, ESLint only offers the mechanism to do something like this:

```js
 /* eslint-disable jsdoc/no-undefined-types */
/**
 * @param {Messages} messages Object containing the messages in chronological order.
 * @returns {processMessage} Function that will handle incoming messages.
 */
export function processMessageWrapper(messages) {
   /* eslint-enable jsdoc/no-undefined-types */
```

Another option would be to add `processMessage` to the `definedTypes` array option.

However, based on your example, it looks like what might want to do is something like this, which should not report any error (and might also work better with jsdoc tooling, though I'm not sure):

```js
/**
 * Processes incoming messages.
 * @callback ProcessMessage
 * @param {string} message Incoming message from stdin.
 */

/**
 * @param {Messages} messages Object containing the messages in chronological order.
 * @returns {ProcessMessage} Function that will handle incoming messages.
 */
export function processMessageWrapper(messages) {
    /**
     * @type {ProcessMessage}
     */
    function processMessage(message) {
```

I.e., I wouldn't think that jsdoc would expect `processMessage` to be accessible by the time it is used, so the above might be the more proper way around it. I'm not fully sure about this, but it is the way I would handle it.

Closing as that should address the main question, but feel free to comment further as needed.

**Comment by Yash-Singh1** [comment]
Could the plugin itself have some sort of internal way of detecting `eslint-disable` comments inside JSDoc comment blocks that will apply to all rules?

**Comment by brettz9** [comment]
@Yash-Singh1 : Hadn't noticed your comment until now, sorry. Yes, we could detect them and process them for eslint-plugin-jsdoc rules when in the same block, but it would only be for our rules, it would be non-standard, and I think it would be a little ugly.

However, where needed, our rules can allow for specifying contexts which indicate which tag or mark-up disables the rule, so if there is a specific rule needing disabling on a per-block basis, we might look to implement if the rule warranted it.
