### ISSUE TITLE
Plan for replacing valid-jsdoc and require-jsdoc

### ISSUE THREAD

**Issue by vibhavsinha** [gajus/eslint-plugin-jsdoc#691]
## Motivation

Eslint rules for `valid-jsdoc` and `require-jsdoc` are [deprecated](https://eslint.org/blog/2018/11/jsdoc-end-of-life).
> The require-jsdoc and valid-jsdoc rules will be deprecated. These two rules will remain in ESLint but we will no longer add new features or fix bugs for them. These rules may be removed in a future major release of ESLint.

## Desired behavior

The official documentation recommends using eslint-plugin-jsdoc for this purpose.
> Suggested Replacement
> If you would like to continue checking JSDoc comments using ESLint, we suggest using the community-supported [eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc) plugin. This plugin contains several rules that are more specific than the core ESLint rules being deprecated and may actually be a better fit for most projects.

**Comment by brettz9** [comment]
Sorry, but what action are you looking for here? ESLint is a separate project from ours, and they already deprecated this as you say. Are you looking for them to remove the rules? If so, you should file with them.

If you are looking for the equivalents in our project, you can see https://github.com/gajus/eslint-plugin-jsdoc/wiki/Comparison-with-deprecated-JSdoc-related-ESLint-rules

**Comment by vibhavsinha** [comment]
Both of these deprecated rules are still in use with this style guide. I am hoping that we can have a change in this project to use alternatives instead of these two rules, or just remove these rules. It is possible to specify the eslint-plugin-jsdoc as part of this configuration.

I have also observed that this project currently does not have any plugins and this might be an intentional decision to keep things simple. Do you see removing these two rules from this configuration in future?

**Comment by vibhavsinha** [comment]
Sorry, I was hoping to make this issue in `google/eslint-config-google`. My bad.
