### ISSUE TITLE
README.md: All rules available not listed under Configuration chapter

### ISSUE THREAD

**Issue by thernstig** [gajus/eslint-plugin-jsdoc#693]
https://github.com/gajus/eslint-plugin-jsdoc start by listing links to all rules. But a bit further down in the README.md https://github.com/gajus/eslint-plugin-jsdoc#configuration under

> Finally, enable all of the rules that you would like to use.

there is missing a few of these rules.

**Comment by brettz9** [comment]
Thank you. I have only found `require-yields-check` missing.

**Comment by thernstig** [comment]
@brettz9 `require-throws` seems to also be missing.

**Comment by brettz9** [comment]
Good reason for getting enough sleep before taking on such issues. :-) Thanks. We also weren't following the convention of adding `require-throws` as explicitly "off" in our main file. (This would only be of consequence, however, if adding the `recommended` config after a config which enabled `require-throws`, as the convention will be for `recommended` to disable its use in such a case.)

**Comment by thernstig** [comment]
@brettz9 Haha yes 😄 I noticed you do you have a generation tool for your README.md. Maybe a future improvement would be to automatically add this there so it never differs again?

**Comment by brettz9** [comment]
A PR is welcome. My plate is already full atm with optimizations I could make. :-)  But may keep it in mind if it irritates me enough next time.

**Comment by thernstig** [comment]
@brettz9 the "new" `sort-tags` is also missing now I see.

**Comment by brettz9** [comment]
@thernstig : Thanks, fixed in #955
