### ISSUE TITLE
[require-jsdoc] Question: Is it possible to not require jsdoc if the interface or abstraction already provide jsdoc?

### ISSUE THREAD

**Issue by Shinigami92** [gajus/eslint-plugin-jsdoc#696]
## Motivation

![image](https://user-images.githubusercontent.com/7195563/108488753-08ed4280-72a1-11eb-95e8-aca88951a05f.png)

## Current behavior

I currently have setup following rule:

```jsonc
    'jsdoc/require-jsdoc': [
      'warn',
      {
        contexts: [
          'ClassDeclaration',
          'ClassProperty:not([accessibility=/(private|protected)/])',
          'ExportNamedDeclaration:has(VariableDeclaration)',
          'FunctionExpression',
          'MethodDefinition:not([accessibility=/(private|protected)/]) > FunctionExpression',
          'TSEnumDeclaration',
          'TSInterfaceDeclaration',
          'TSMethodSignature',
          // 'TSPropertySignature',
          'TSTypeAliasDeclaration'
        ]
      }
    ]
```

Sadly I don't see an option to prevent the need of writing jsdoc if the implemented interface or abstract class already provides JSDoc.  
And I don't want to duplicate the JSDoc everywhere.

## Desired behavior

Any kind of possibility to not warn when the function that is implemented already provides jsdoc, **without the need** of `eslint-disable-next-line`

**Comment by brettz9** [comment]
ESLint does not really provide tools for following around variables throughout a program. You might see if https://www.npmjs.com/package/@typescript-eslint/eslint-plugin or maybe the https://tsdoc.org/ folks were interested in implementing such a rule.

While this wouldn't prevent the need for adding a jsdoc block, the closest behavior we support would be that that if you did add:

```js
/**
 * @implements {...}
 */
```

...various other rules like `require-param` or `require-returns` will avoid reporting on that block (unless you explicitly set `{settings: {jsdoc: {overrideReplacesDocs: false}}}`).

But that is more of a generic jsdoc-based solution, not a fully TypeScript-aware one.

**Comment by Shinigami92** [comment]
You introduced me to the use of `/** @inheritdoc */` :tada: 
This is at least an option for me :heart: 

I need to add it to many places but I think that's okay and also tells other devs in my team that it is intended

---

Maybe TS can be feed with an `esquery` `override` property when https://github.com/microsoft/TypeScript/pull/39669 is released :thinking: 

---

You can close this issue if you like, or keep track with it and someday it can be implemented as a really nice improvement

**Comment by brettz9** [comment]
Sorry, but I think I should close this simply because I don't think there is any easy way for such tracing to be done with ESLint which does not trace or provide facilities to trace an entire interconnected program as TypeScript (or semmle) may do. If it becomes possible, we can reopen at such time.
