### ISSUE TITLE
jsdoc/no-undefined-types

### ISSUE THREAD

**Issue by hieuvp** [gajus/eslint-plugin-jsdoc#70]
It happens only in the latest release `3.6.2`. What is wrong?

```
   3:1   warning  The type 'Array' is undefined             jsdoc/no-undefined-types
   3:1   warning  The type 'Object' is undefined            jsdoc/no-undefined-types
```

```javascript
/**
 * @param {Array<string>} args
 * @param {Object} opts
 * @param {boolean} opts.ci
 * @param {boolean} opts.fix
 */
```

**Comment by bary12** [comment]
Only happens in `3.6.2` but does not happen in `3.6.1/3.6.0`? `no-undefined-types` was added in `3.6.0`.

I also got this error on my project but was not able to replicate it in the tests. Can you provide your configuration file?

**Comment by hieuvp** [comment]
I have just `npm install` my project today and got these warnings.

```
plugins: [
    'jsdoc',
    'prettier'
],
  extends: [
    'airbnb-base'
    'plugin:jsdoc/recommended',
    'plugin:prettier/recommended'
  ],
```

cc: @bary12

**Comment by bary12** [comment]
Is this your entire config or do you have env, parserOptions, etc?

**Comment by bary12** [comment]
Seems to be caused by "sourceType": "module"

**Comment by bary12** [comment]
@gajus next time when new rules are added to the recommended preset, a major version increment is needed, as the rules will automatically be applied and it can break CIs.

**Comment by hieuvp** [comment]
Finally you figure it out.

Thank you, @bary12
