### ISSUE TITLE
Question: Is there any way we could work together to achive typed rule support in `eslint-define-config`?

### ISSUE THREAD

**Issue by Shinigami92** [gajus/eslint-plugin-jsdoc#708]
Hi 🙂 I'm the author of https://github.com/Shinigami92/eslint-define-config

Do you think it's possible in any way to work together on https://github.com/Shinigami92/eslint-define-config/tree/main/src/rules/jsdoc and https://github.com/Shinigami92/eslint-define-config/blob/main/src/settings/jsdoc.d.ts?

Contributions in any way are really welcome 😃

**Comment by Shinigami92** [comment]
@brettz9 I'm also willing to give you a write invitation to the repo 🙂

**Comment by brettz9** [comment]
Nice project!

If @gajus is ok with it, I'd think for uses such as this, we'd be justified in exporting such type files ourselves? I assume you could import our types?

For the rules, I'd very much suggest this approach so we can just use the schemas that are a part of the files:

1. Iterate through the rule directory
2. Use [esquery](https://www.npmjs.com/package/esquery) to find any schema object within the file.
3. Use [json-schema-to-typescript](https://www.npmjs.com/package/json-schema-to-typescript) to build the TypeScript for that schema object.

This has the additional advantage of easy future maintenance as well (and may be similar for other ESLint plugins).

**Comment by Shinigami92** [comment]
As long as the types package doesn't have direct `dependencies` I think I can import them.
Currently the `.d.ts` files are directly served and not `transpiled` by `tsc`.
So I try to not bring runtime `dependencies` with my `package` but only compile time `devDependencies`.
But if a package, like your suggested types are only these - types, not-runtime-code - I think this is okay.

**Comment by brettz9** [comment]
Right, a build step on our end is the idea.

**Comment by brettz9** [comment]
Btw, as useful as I very much think this project is, I've got a lot on my plate right now (for what I am able to do), so I don't know about my chances of getting to this, at least for some time.

**Comment by Shinigami92** [comment]
As I have time and I'm board, I just update and add some rules here and there

JSDoc progress is currently as followes:

- Settings: https://github.com/Shinigami92/eslint-define-config/blob/main/src/settings/jsdoc.d.ts
- Rules: https://github.com/Shinigami92/eslint-define-config/tree/main/src/rules/jsdoc

My progress from yesterday looks like this 😄   
https://github.com/Shinigami92/eslint-define-config/compare/1.0.5...1.0.6

**Comment by brettz9** [comment]
When you're free, @Shinigami92 , I've come up with https://github.com/brettz9/eslint-plugin-jsdoc/commit/6907712485b7258c75a768e5902d62ac1128b7ec to ensure we are building the TS files directly from our internal JSON Schema files. Hopefully, it is just a matter then of adding some more boilerplate for the declaration files to be complete?

**Comment by Shinigami92** [comment]
@brettz9 Oh I'm sorry I forgot this issue and did not closed it

In the last year we already developed a script that extracts automatically all the meta info that is needed to generate the .d.ts files for eslint-define-config

I'm also not sure if I could use external type declarations via dependency, due to I'm not sure if then the dependency is needed and there are no optional peer dependencies for types I assume
However I did not tested that

Right now we are supporting 23 eslint plugins including [eslint-plugin-jsdoc](https://github.com/Shinigami92/eslint-define-config/blob/7a3e66336b7697eb2cc7d3a22d2f0d02d158e9e7/scripts/generate-rule-files/src/plugins-map.ts#L33-L37)

But anyway, to have TS types is always a good thing I assume, so I hope I did not waste your time 🙇
