### ISSUE TITLE
allow more "require" for fields

### ISSUE THREAD

**Issue by lublak** [gajus/eslint-plugin-jsdoc#717]
## Motivation

To better enforce documentation straight for fields.

## Current behavior

Currenlty it is impossible to force this behaviour (`@type` for fields):

https://jsdoc.app/tags-type.html

Currently if i use match-description
```json
"jsdoc/match-description": [
    "error",
    {
        "matchDescription": "^[a-zA-Z0-9_\\- /\\\\()[\\]{}=?!:.,;*+~#'\"%&<>|]+$",
         "contexts": [
               "any"
         ]
    }
],
```
but this does not work (as a side note: this also does not apply to the class description).

the require-jsdoc works fine:

```json
"jsdoc/require-jsdoc": [
    "error",
    {
        "publicOnly": true,
        "require": {
            "ArrowFunctionExpression": true,
            "ClassDeclaration": true,
            "ClassExpression": true,
            "FunctionDeclaration": true,
            "FunctionExpression": true,
            "MethodDefinition": false
        },
        "contexts": [
            "MethodDefinition:not([accessibility=\"private\"]) > FunctionExpression",
            "ClassProperty:not([accessibility=\"private\"])",
            "TSPropertySignature"
        ]
    }
],
```

## Desired behavior

I want to force fields to have a description and what type they contain.

## Alternatives considered

The only alternative is to control it manually.

**Comment by brettz9** [comment]
Can you provide some sample jsdoc that you are trying to enforce and which fails?

Your regular expression in `match-description` doesn't *require* that a type exist even if the rule were to match more than descriptions. Or are you merely suggesting that the matching doesn't work when `contexts: ['any']` is present? If so, please provide an exact sample where it fails.

Also in your issue title, please clarify the specific rule(s) you are asking for more `require` cases, e.g., if for `match-description`.

Please note that with the jsdoc setting [`structuredTags`](https://github.com/gajus/eslint-plugin-jsdoc/#eslint-plugin-jsdoc-settings-structuredtags), you can require which tags must have a `type` (items no. 1 and 2 indicate the default tags where it is or can be required per the `jsdoc/valid-types` rule).

**Comment by lublak** [comment]
@brettz9 
Sorry, my English is not the best and I have a hard time explaining myself.

I fixed a problem myself because I forgot to also set `require-description` to `"contexts": [ "any" ]`.

Now i want `@type` {string} to be enforced in public fields under the description.

Should throw an error: Missing `@type`
![grafik](https://user-images.githubusercontent.com/44057030/116403798-4d133b00-a82e-11eb-9ebd-ceb82c02eb55.png)

And everything is fine here:
![grafik](https://user-images.githubusercontent.com/44057030/116404156-a8452d80-a82e-11eb-9584-83687b928080.png)

But you already said it was possible. Then I'll have to take a closer look.
It's a bit confusing.

And thank you for your patience. <3

**Comment by brettz9** [comment]
> @brettz9
> Sorry, my English is not the best and I have a hard time explaining myself.

No worries, you are doing just fine. :-) Just wanted more examples which you've given.
 
> Now i want `@type` {string} to be enforced in public fields under the description.
> <snip>
> 
> But you already said it was possible. Then I'll have to take a closer look.

Actually, I had not understood your intent. I was speaking about the ability to require that a type (the part within the curly brackets) is always present when specific tags are used (e.g., if you use `@type`, there must be a `{SomeType}` with the tag as when you use `@implements`). But that mechanism won't report that a particular tag (including `@type`) is required for a particular structure. That request can be considered a dupe of the non-global part of #467 . Feel free to subscribe there in case we may implement this in the future.
