### ISSUE TITLE
Feature Request: Require single line JSDoc for short comments

### ISSUE THREAD

**Issue by danvk** [gajus/eslint-plugin-jsdoc#724]
## Motivation

There are two basic forms of JSDoc comment:

```ts
/** single line */

/**
 * multiline
 * jsdoc
 * comment
 */
```

For short comments, I consider the multiline form a waste of space. For example, instead of:

```ts
/**
 * Process the inputs and return an output.
 */
function f(x) { ... }
```

I'd like to enforce that this be written using single line form:

```ts
/** Process the inputs and return an output. */
function f(x) { ... }
```

## Current behavior

I believe this would have to be a new rule.

## Desired behavior

I'd like to be able to configure a maximum line length for JSDoc comments and have eslint-plugin-jsdoc enforce that JSDoc comments shorter than this use the single-line form, whereas JSDoc comments longer than this use the multiline form.

Configuration might be something like:

```js
{
  'jsdoc/prefer-single-line': ['error', 'always', {
    maxLineLength: 95
  }]
}
```

## Alternatives considered

None

**Comment by brettz9** [comment]
Sure, as you like. I'll go ahead and summarize your idea in that same comment, as I've turned it into a kind of wiki.
