### ISSUE TITLE
Need a way to get `require-param` to exempt `@override`

### ISSUE THREAD

**Issue by rsimha** [gajus/eslint-plugin-jsdoc#73]
Hi @gajus, nice work in creating `eslint-plugin-jsdoc`! The [AMP project](https://www.ampproject.org/) just adopted it as our primary JSDoc checker, and it's working quite nicely for us. However, there's one really visible problem:

As described in https://github.com/ampproject/amphtml/issues/15297, the [Google JS style guide](https://google.github.io/styleguide/jsguide.html) prefers `@override` over `@inheritdoc`.

From [here](https://google.github.io/styleguide/jsguide.html#features-functions-parameters):

> Function parameters must be typed with JSDoc annotations in the JSDoc preceding the function’s definition, except in the case of same-signature `@override`s, where all types are omitted.

From [here](https://google.github.io/styleguide/jsguide.html#jsdoc-method-and-function-comments):

> Overridden methods must include all `@param` and `@return` annotations if any types are refined, but should omit them if the types are all the same.

And from [here](https://google.github.io/styleguide/jsguide.html#appendices-notes-about-standard-closure-compiler-annotations):

> `@inheritDoc` | Deprecated. Do not use. Use `@override` instead.

However, from looking at the source code of the `jsdoc/require-param` rule, it's clear that only `@inheritdoc` tags are exempted from documenting their `@param`s.

https://github.com/gajus/eslint-plugin-jsdoc/blob/52e3fcc46dd4087e50acf4a0c4f5683d51f5a699/src/rules/requireParam.js#L11-L14

I realize this is essentially a disparity between the JSDoc documentation and the Google style guide. However, we're seeing [hundreds of errors](https://github.com/ampproject/amphtml/search?l=JavaScript&q=%22%40override%22&type=Code) from using `@override` in our source code even though the Google style guide recommends it.

I was wondering if an exception could be made for `@override` in the `require-param` rule. Something gated by a setting would work too. Would you be willing to accept a PR that implements this?

Related to https://github.com/gajus/eslint-plugin-jsdoc/issues/20

**Comment by gajus** [comment]
> I was wondering if an exception could be made for @override in the require-param rule. Something gated by a setting would work too. Would you be willing to accept a PR that implements this?

Yes, a setting-guarded exception is completely acceptable.

**Comment by rsimha** [comment]
Great, thanks! I've implemented a setting-guarded exception in #74.
