### ISSUE TITLE
Feature-Request: `tag-lines` depending on the tag

### ISSUE THREAD

**Issue by jens-duttke** [gajus/eslint-plugin-jsdoc#734]
## Motivation

Be able to make a more granular configuration, depending on the tag type.

## Current behavior

There is only one configuration for all tags.

## Desired behavior

It would be nice if there would be a by-tag configuration, so that I can use an array or regexp to specify a list of tags, and their behaviour.

e.g. I want that there is an empty line after `@file` and `@example`, but not between `@param`s

## Alternatives considered

There could be two new optional properties called "always" and "never", which accept an array of tag names, like:
```
"always": ["file", "example"],
"never": ["params"]
```
Or an option "inverse", which also accepts an array of tag names, and inverse the configured behaviour for these tags:
```
"tag-lines": ["error", "never", { "inverse": ["file", "example"] }]
```

**Comment by brettz9** [comment]
No promises to implement, but I would suggest a `tags` option with each key being a tag and the value an object with `lines` being set to "always" or "never", and `count` also being available on that object (to override the default if desired) as well.
