### ISSUE TITLE
Add jsdoc/comment-style-whitespace rule

### ISSUE THREAD

**Issue by sobolevn** [gajus/eslint-plugin-jsdoc#76]
Currently both 

```
/**
*
*/
```

and

```
/**
 *
 */
```

Are considered valid. I would really like to have a rule to enforce first or second way of defining `jsdoc` comment blocks.

Related: https://github.com/wemake-services/wemake-vue-template/issues/493

**Comment by gajus** [comment]
Sounds like a simple rule. PR welcome.

**Comment by golopot** [comment]
Closed by #186
