### ISSUE TITLE
require-jsdoc fixer improvement: customizable fixer text

### ISSUE THREAD

**Issue by schmetzyannick** [gajus/eslint-plugin-jsdoc#764]
Would you be open for a Pull request, which changes the fixer of the require-jsdoc rule?

At the moment, the fixer is adding a comment like this: 
```
/**
 *
 */
```

I would like the comment to be something like: 
```

/**
 * TODO: fix jsdoc/require-jsdoc
 */
```
 
 So you can search in your IDE, which comments should be corrected.

**Comment by brettz9** [comment]
I think you would be welcome to provide a PR for a `fixerText` option which, if present, will be added (after a space), e.g., `fixerText: 'TODO: fix jsdoc/require-jsdoc'`. However, the option should not be applied by default, as it can be useful as it is now for those who don't want to bother with function descriptions but who do want `@param` and such required by other rules, to have those flagged once a JSDoc block has been added.

**Comment by schmetzyannick** [comment]
I will try to find some this week to provide a PR.

**Comment by schmetzyannick** [comment]
What do you think about a fixer for the require-param-description rule, which also could get a default message?  It should not be to hard. I would just append the provided message to the @param comment line.

**Comment by brettz9** [comment]
Closed by #766 .  Thanks much for the PR!
