### ISSUE TITLE
Reenable other Node.js versions

### ISSUE THREAD

**Issue by gajus** [gajus/eslint-plugin-jsdoc#801]
I couldn't get build to pass using test matrix.

For whatever reason tests running in other Node.js versions are not properly initialized.

https://app.travis-ci.com/github/gajus/eslint-plugin-jsdoc/jobs/545084937

[This commit](https://github.com/gajus/eslint-plugin-jsdoc/commit/f1bb1ab5bfd8f943638b146733fc6517e4ca7a17) should be reverted once the underlying issue is understood.

**Comment by brettz9** [comment]
@gajus : In case you may get to it before I may, it seems the tests started failing in a8387beb91651d59f199ed73f65a84ebe1526c32
