### ISSUE TITLE
Add support for requiring tags like todo to have a value

### ISSUE THREAD

**Issue by dasa** [gajus/eslint-plugin-jsdoc#802]
## Motivation

I want `@todo` to be an error, and `@todo xyz` to not be an error.

## Alternatives considered

I tried using `match-description` with `todo` added to `tags`, but this also started erroring on `constructor` unless I also used `constructor: ".*"`, even though I set `mainDescription` to `false`.

**Comment by brettz9** [comment]
You had the right idea in what you tried. There was a bug with the `mainDescription` handling. This should now be fixed, including with `@constructor`. Fixed in v37.4.2
