### ISSUE TITLE
require-jsdoc: exempt functions with no arguments and a return value

### ISSUE THREAD

**Issue by briandipalma** [gajus/eslint-plugin-jsdoc#807]
## Motivation

To stop adding empty JSDoc blocks when fixing files.

## Current behavior

Using this config:

    `"jsdoc/require-jsdoc": ["warn", { exemptEmptyFunctions: true }],`

ESLint fixing is adding empty JSDoc blocks to functions that have no parameters but return a value. I'd rather not have an empty JSDoc block added if possible so a more general option around that would be perfect but if not a new, more specific option like `exemptNoParameterFunctions` would also fix this issue. I mostly document to provide TS type information as the majority of the code I work isn't public API.

## Desired behavior

No empty JSDoc blocks being added

## Alternatives considered

I disabled the fixer but that means useful JSDoc blocks aren't added.

**Comment by brettz9** [comment]
I'm not sure we want to be adding more pre-baked options, but you should be able to get what you want using the  `contexts` option. See the docs, and particularly the [AST explorer tool](https://astexplorer.net/) for assistance.

For example, you might include `FunctionDeclaration[params.0]` as your context for function declarations as it checks that there is at least one parameter (and also set the `FunctionDeclaration` in `require` to `false` so it stops checking for parameterless ones).

Closing as that should resolve but feel free to comment further.
