### ISSUE TITLE
Question: TemplateLiterals

### ISSUE THREAD

**Issue by brokentone** [gajus/eslint-plugin-jsdoc#84]
Noticing in your [canonical eslint config](https://github.com/gajus/eslint-config-canonical/blob/master/configurations/eslintrc.json#L447-L450) a restriction on using `TemplateLiteral`s. Not here to debate JS style, but I feel that literals would provide cleaner error report messages. Have opinions changed on their usage, or still verboten?

**Comment by gajus** [comment]
Can you provide a use case example?

I do use template literals often in specific cases, e.g. describing test cases or as a way to escape text (https://github.com/gajus/slonik#tagged-template-literals). However, I never use it for simple string interpolation.
