### ISSUE TITLE
Property context isn't working

### ISSUE THREAD

**Issue by TimJ0212** [gajus/eslint-plugin-jsdoc#841]
I want to lint uncommented properties. For this, I use the `require-jsdoc` rule.
In the context of the rule I use the given text `Property` which is in the [documentation](https://github.com/gajus/eslint-plugin-jsdoc#contexts-7) of the rule in the context section.  But he doesn't lint my uncommented properties.
Thank you  for this nice project.

My configuration:
```
"jsdoc/require-jsdoc": [
             "error",
              {
              "contexts": [
                       "Property"
               ],
              "require": {
                   "ClassDeclaration": true
               },
                    "publicOnly": true,
                    "checkConstructors": false
               }
  ],

**Comment by brettz9** [comment]
Please provide the requested information. You have not provided any code that you expect to trigger.

**Comment by brettz9** [comment]
Closing until providing the required information.

**Comment by TimJ0212** [comment]
Sorry, I'm working with ts and wrote:

> 
> /**
>  \* Some comment.
>  \* /
> export class Component {
> &nbsp;&nbsp;&nbsp;&nbsp;public foo?: number;
> }

I expected foo to trigger, but I don't get anything linted.

**Comment by TimJ0212** [comment]
Sorry to bother you again. But the changes unfortunately have no effect on the behavior. I have applied the configuration of your changes:

`"jsdoc/require-jsdoc": ["error", {"checkConstructors":false,"contexts":["PropertyDefinition"],"publicOnly":true}]`

And my code remains the same:

```
/**
 * Some comment.
 */
export class Component {
    public foo?: number;
}
```

I expect the foo to be linted because no comment is provided. What is my error?

Do you have any idea why it still doesn't work? In related issues, the ECMAScript version was often mentioned, I use es2015. Can this be related to that?

With kind regards

**Comment by brettz9** [comment]
I have reconfirmed that your exact example is indeed now reporting an error as expected.

If you are linting within an IDE, have you restarted the IDE? Some IDEs require this for the updates to take effect.

If you are still seeing an issue despite running `npm install` and restarting your IDE if using an IDE, then I think we'd need a minimal reproducible example repo to see if some other subtle configuration was causing an issue.

Re: the ES version, as long as you are using the TypeScript parser (which you need for your code), you shouldn't be getting any complaints, at least from ESLint, related to your choice of `ecmaVersion`. ES2015 added module support, so unless using dynamic imports, which were added later, you should be fine.

**Comment by brettz9** [comment]
You might also try removing your `node_modules` and package lock file and doing a fresh `npm install` to ensure you have the latest dependencies. I wouldn't expect this to be necessary, but it may be worth a try if you're still seeing an issue.

**Comment by TimJ0212** [comment]
Thank you for your quick responses. Sponsor you now, really top.
I have a nx workspace with multiple Angular projects, and I was able to get the correct behavior on a new Angular project and on a new nx workspace.
In the affected workspace I deactivated all other rules, also this brings no change. Would you have any idea what else I might be able to test? I am running out of ideas.

I have deleted and reinstalled the `node_modules` folder several times. In my `package.json` I use the latest version.
Are there any conflict configurations that I missed?

Thank you!!

**Comment by brettz9** [comment]
> Thank you for your quick responses. Sponsor you now, really top.

Appreciate the sponsorship, thank you. But so you know, I can't guarantee I can always be super responsive, though I do hope to be for issues that are simple enough to resolve.

> I have a nx workspace with multiple Angular projects, and I was able to get the correct behavior on a new Angular project and on a new nx workspace. In the affected workspace I deactivated all other rules, also this brings no change. Would you have any idea what else I might be able to test? I am running out of ideas.
> 
> I have deleted and reinstalled the `node_modules` folder several times. In my `package.json` I use the latest version. Are there any conflict configurations that I missed?

Hmm. Other nx users reporting a similar problem on #786 though not really sure that would be related. Are you able to report an issue to them or find a support chat or StackOverflow question about it?

**Comment by brettz9** [comment]
Do you have complex eslintrc settings where one config could be overriding another?
