### ISSUE TITLE
Working with Emacs

### ISSUE THREAD

**Issue by trev-dev** [gajus/eslint-plugin-jsdoc#843]
I can get this plugin to work well with VSCode, but when I try to use it with lsp-mode in Emacs, flycheck tilts and shows a red "!".

I spent some time configuring lsp-mode to stay out of eslint, and to just enable ordinary javascript-eslint with flycheck. That got the warning hints to actually show up in JS-Mode, but now subtle nuances are list (like importing a typedefs.js).

I'm not even sure where to start with this problem. Has anyone managed to get things working with emacs lsp-mode?

**Comment by spenserw** [comment]
I am unfortunately dealing with this issue as well. I was able to narrow it down (at least in my case) to the rule `jsdoc/require-jsdoc`... Disabling this rule allows lsp-mode to display errors properly again, even while still extending `plugin:jsdoc/recommended`. Anyone have any idea what this rule may do differently?

**Comment by brettz9** [comment]
Have what I think should be a fix coming your way shortly. Let me know if it works.

**Comment by spenserw** [comment]
@brettz9 Wow, quick turnaround! Unfortunately this did not fix the issue for me. Anytime `jsdoc/require-jsdoc` is caught by the linter, all of my errors no longer display. Disabling the rule or removing the error restores proper error display.

I confirmed this on 39.2.4 and 39.2.5.

**Comment by brettz9** [comment]
Ah, that makes sense. I was focused on ensuring it did cover the whole line (as a prior issue had requested that), but as long as the line is one higher, there can, and apparently, should, always be some column too. Thanks!

**Comment by brettz9** [comment]
@trev-dev : Let us know if that release fixes your issue. We can reopen if not.

**Comment by spenserw** [comment]
@brettz9 Interesting. I don't know much about eslint internals, just decided to poke around the area you edited. Thanks for dealing with all of this so promptly!
