### ISSUE TITLE
Automatic Line Breaks

### ISSUE THREAD

**Issue by Zamiell** [gajus/eslint-plugin-jsdoc#849]
Prettier automatically breaks up long lines of code. This is fantastic, and saves developers tremendous amounts of time. Anyone who has used Prettier for a while knows how much of a drain it is to do this manually.

However, Prettier doesn't currently break up long lines on JSDoc comments.

For example, the following JSDoc comment:

![image](https://user-images.githubusercontent.com/5511220/157912894-a3a10ea8-d4cf-4102-91c2-71f155b03aed.png)

Should be instead formatted like this:

![image](https://user-images.githubusercontent.com/5511220/157913406-e2dd817b-d1a5-4ccb-8d3b-8e3867c2977e.png)

If this plugin could perform this transformation for me automatically when I save the file, it would save me an *enormous* amount of time.

**Comment by Zamiell** [comment]
I made this rule here: https://github.com/IsaacScript/isaacscript/blob/main/packages/eslint-plugin-isaacscript/docs/rules/format-jsdoc-comments.md

**Comment by brettz9** [comment]
Excellent! Feel free to submit your tool to [awesome-jsdoc](https://github.com/brettz9/awesome-jsdoc) and [awesome-eslint](https://github.com/dustinspecker/awesome-eslint) and/or submit as a PR to `eslint-plugin-jsdoc`. If not the latter, feel free to close the issue. Thanks for sharing!

**Comment by Zamiell** [comment]
It's probably not a good fit for JSDoc since it uses the same code to auto format line comments too.

**Comment by brettz9** [comment]
Ok, FWIW, I've listed your tool at https://github.com/brettz9/awesome-jsdoc
