### ISSUE TITLE
New rule to ensure that arrays, objects, and Promises specify the type they contain

### ISSUE THREAD

**Issue by garyking** [gajus/eslint-plugin-jsdoc#87]
Please add a new rule, which would disallow `@param {Array}`, and instead require `@param {string[]}`, so that the type of items in the array is explicitly specified. The default would therefore be `@param {any[]}`.

And for objects, rather than `@param {Object}`, require `@param {Object<string, number>}` instead.

Thanks!

**Comment by brettz9** [comment]
I think this should be expanded to support `Promise<void>` and optionally allowing for the other array syntax `Array.<string>`.
