### ISSUE TITLE
Constructor jsdoc problem

### ISSUE THREAD

**Issue by xJonahS** [gajus/eslint-plugin-jsdoc#872]
## Problem
jsdoc is throwing an error for the following line of code, even tho there is a jsdoc in place:
![image](https://user-images.githubusercontent.com/58333113/163168759-0ff00f3b-4424-440a-aa05-af50f085d668.png)

The problem is not present in `v39.1.1` and started with `v39.2.0`.
## Expected behavior
Everything should be fine.
## Actual behavior
Error is thrown:
![image](https://user-images.githubusercontent.com/58333113/163168608-71182435-e462-43da-8f8f-89eaa80d6627.png)

Error seems to be related to this change in version `39.2.0`:
![image](https://user-images.githubusercontent.com/58333113/163168956-c08beaca-24d4-412e-8304-b9da8e7f8087.png)

## Environment

- `Node` version: v16.13.2
- `ESLint` version: v8.13.0
- `eslint-plugin-jsdoc` version: 39.2.0

Thank you in advance 🙂

**Comment by brettz9** [comment]
What parser are you using?

**Comment by brettz9** [comment]
I assume it's `@typescript-eslint/parser` but I can't replicate. Can you provide a shorter sample that triggers the problem?

**Comment by xJonahS** [comment]
Its `@typescript-eslint/parser` v5.19.0 which i also upgraded from version v5.10.0 . I will try to find a shorter sample for you.

**Comment by brettz9** [comment]
Nevermind, replicated it. Should have a fix shortly.

**Comment by xJonahS** [comment]
Thank you very much!

**Comment by brettz9** [comment]
Thanks for the report; fixed by 041de5f224773756edb4a658a791ae99eecfc3bf . Released in v39.2.1 .
