### ISSUE TITLE
valid-types cannot valid  combination type

### ISSUE THREAD

**Issue by kaocong** [gajus/eslint-plugin-jsdoc#889]
## Environment

- Node version: v14.19.3
- ESLint version v7.32.0
- `eslint-plugin-jsdoc` version: "39.3.2"
- 
![image](https://user-images.githubusercontent.com/50489475/170432106-e7421363-87be-453d-bda9-26121fab519d.png)
``` js
/**
 * @param {HTMLElement & CustomElement} el 
 */

ESLint: Syntax error in type: HTMLElement & CustomElement(jsdoc/valid-types)
```

Why do I write that ？
Because I want to inherit HTMLElement and add attributes

**Comment by brettz9** [comment]
The intersection type is only valid for TypeScript mode. If you are not using `@typescript-eslint/parser` as your parser, you need to set:

```js
settings: {
  jsdoc: {
    mode: 'typescript'
  }
}
```

**Comment by kaocong** [comment]
> ```js
>  mode: 'typescript'
> ```

it works，thx
