### ISSUE TITLE
report an error when a package imported in a `@type` is not present in `package.json`

### ISSUE THREAD

**Issue by DetachHead** [gajus/eslint-plugin-jsdoc#896]
## Motivation
i use [`import/no-extraneous-dependencies`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md) to ensure that i don't accidentally install and import dependencies without adding to `package.json`.

it would be nice to have that functionality in jsdoc `@type`s as well

## Current behavior
no error when `eslint` and/or `@types/eslint` is not present in `dependencies` or `devDependencies` in `package.json
```js
/** @type {import('eslint').Linter.ParserOptions} */
const foo = {}
```

## Desired behavior
error

## Alternatives considered
raised an issue on `eslint-plugin-import` but it was suggested that i raise it here as it's apparently not able to check jsdocs - https://github.com/import-js/eslint-plugin-import/issues/2508#issuecomment-1193764236

**Comment by brettz9** [comment]
Is this intended to catch the problem just a little earlier than running the compiler? Because TypeScript will, as I recall, report this kind of mistake if one is checking even plain JavaScript.

**Comment by DetachHead** [comment]
@brettz9 its for transitive dependencies which the typescript compiler won't catch. In my example with the `eslint` type import, if I have another dependency that depends on `eslint` but `eslint` itself is not in my `package.json`'s `dependencies` section, typescript won't care

**Comment by brettz9** [comment]
Ok, and you care about adding dependencies directly in case the transitive ones are ever removed by other dependencies?

**Comment by DetachHead** [comment]
Yep exactly. Another case I just remembered is when I remove a dependency from my `package.json` and forget to remove all of its imports, then all my tests still pass locally because I didn't actually uninstall it yet.
