### ISSUE TITLE
rule to require @description on functions and classes

### ISSUE THREAD

**Issue by ajelcocks** [gajus/eslint-plugin-jsdoc#90]
I have searched everywhere to see if there is a way to enforce a description is added to each function and class declaration. @description seems to be optional but I see no way of requiring it. If this is not possible would you consider adding it as a new rule? jsdoc/require-description:1 ?

**Comment by gajus** [comment]
> If this is not possible would you consider adding it as a new rule? jsdoc/require-description.

Yes, go ahead.

**Comment by ajelcocks** [comment]
Hi
I cloned and created a local branch.
I have tested in a project and run unit tests

What do I do next?
push the branch I created?
I  named it "Add-require-description"

Thanks

**Comment by gajus** [comment]
https://help.github.com/articles/creating-a-pull-request/

^ Provides step-by-step description.

**Comment by brettz9** [comment]
`require-description` matches this for functions but not for classes.
