### ISSUE TITLE
Require description and type on `@throws` tag

### ISSUE THREAD

**Issue by ericcornelissen** [gajus/eslint-plugin-jsdoc#911]
## Motivation

I would like to use this plugin to enforce the same on the use of `@throws` tags as I can enforce on `@returns`, `@param`, and `@property` tags. By that I mean, in addition to the [`require-throws` rule] I would like to see the rules:

- `require-throws-description`: Requires that the `@throws` tag has a description value.
- `require-throws-type`: Requires that `@throws` tag has type value.

## Current behavior

The [`require-throws` rule] just enforces that the `@throws` tag is used. If the [`match-description` rule] is also used the description may be enforced as well.

## Desired behavior

The plugin can be used to enforce:

1. _A_ description is provided for `@throws` (rather than the specific description format enforced by the [`match-description` rule], similar to `require-param-description` etc.).
2. A type is provided for `@throws`.

## Alternatives considered

1. Using the [`match-description` rule] to enforce a description on `@throws`.
2. None

[`match-description` rule]: https://github.com/gajus/eslint-plugin-jsdoc/tree/05b0928fea4165854d24b6963adf8241c071b5a0#user-content-eslint-plugin-jsdoc-rules-match-description
[`require-throws` rule]: https://github.com/gajus/eslint-plugin-jsdoc/tree/05b0928fea4165854d24b6963adf8241c071b5a0#user-content-eslint-plugin-jsdoc-rules-require-throws

**Comment by brettz9** [comment]
Regarding `require-throws-type`, you can get this with the `structuredTags ` setting. See https://github.com/gajus/eslint-plugin-jsdoc/pull/906#issuecomment-1226346835 .

As far as `require-throws-description`, you can override the `match-description` behavior to use your own (optionally per-tag) regular expression, including something as simple as `.+` to enforce the presence of any description. See the rule for details.

Closing as that should resolve, though feel free to comment further as needed.

**Comment by ericcornelissen** [comment]
Thanks for the quick response and link to the PR (I had only searched through issues :sweat_smile:)! Using the `structuredTags` and `match-description` works for me.

That being said, it does seem odd to me that `@returns`, `@param`, and `@property` get custom rules for this exact purpose. Is there a particular motivation for this, or should those rules perhaps be deprecated? Just a thought really - I (will) appreciate the work on this plugin nonetheless! :smile:

**Comment by brettz9** [comment]
Sure. The rules for `@param` type, etc., have been long-standing rules and I think are more basic to a diversity of projects, even though I acknowledge it is good practice to enforce for `@throws` too where possible (projects may really have to go digging to find and keep up to date all the possible `@throws` types, however, given that any call made within a block may cause its own errors to be thrown).

We could deprecate the stated rules, but I'd rather avoid too many breaking changes, while still avoiding new rules which can already be handled.
