### ISSUE TITLE
Invitation to move to official `eslint-community` org

### ISSUE THREAD

**Issue by MichaelDeBoey** [gajus/eslint-plugin-jsdoc#912]
It's up to you —@gajus—, but if you'd like, you're welcome to transfer this repository to the official [`@eslint-community` organization on GitHub](https://github.com/eslint-community).

As you can read in [the '`@eslint-community` GitHub organization' RFC](https://github.com/eslint/rfcs/tree/main/designs/2022-community-eslint-org), the goal of this new org is to have a place where community members can help ensure widely depended upon ESLint related packages stay up to date with newer ESLint releases and doesn't hold the wider community back without depending on one person's GitHub/`npm` account.

Again, totally up to you. I just want you to know we appreciate all you've done and you're welcome to join the organization if you like.

**Comment by gajus** [comment]
Thank you, no.

**Comment by MichaelDeBoey** [comment]
No problem.

If you ever would want to transfer the repos to the new org, you're always welcome to do so.

**Comment by MichaelDeBoey** [comment]
@gajus Now that ESLint has removed some core rules in favor of this plugin in https://github.com/eslint/eslint/issues/15820, I wanted to ask again if you would be up for moving this plugin repo to the official @eslint-community org as we already do this for other packages/plugins that got extracted out of the core repo as well

The package will still be called the same, the only change would be where the repo is living, that's all
