### ISSUE TITLE
require-param option "allOrNone"

### ISSUE THREAD

**Issue by Zamiell** [gajus/eslint-plugin-jsdoc#920]
Currently, the `require-param` rule requires that every function in an entire codebase has an associated JSDoc param. I would imagine that this default behavior is overboard for most people, causing them to not use the rule at all. However, it is also common to write JSDoc comments for your publicly exported functions. When doing so, developers can fall into the trap of:

```ts
/**
 * @param foo Some number.
 * @param bar Some number.
 */
export function myPublicFunction(foo: number, bar: number, baz: number) {}
```

Oops! We forgot to write a comment for `baz`, which is a bug in our code. This is exactly the kind of thing that the `require-param` rule will lint. But turning on `require-param` isn't helpful here, because the vast majority of our codebase doesn't have any JSDoc comments at all.

What we really want is the `require-pram` rule to only throw an error if:
1) one or more JSDoc `@param` tags exist
2) AND one or more `@param` tags are missing.
This functionality could be gated behind an option called `allOrNone`. (Maybe it could be named better.)

Brett and I discussed this a few months back, and he recommended that I simply utilize the `context` part of the rule, and that way `eslint-plugin-jsdoc` would not have to have a custom option. He specifically recommended the following context:

```ts
contexts: [
  {
    context: "FunctionDeclaration",
    comment: 'JsdocBlock > JsdocTag[tag="param"]',
  },
],
```

I am testing out this context on the latest version of  `eslint-plugin-jsdoc`, but it doesn't seem to work at all. I am not quite sure why it does not work, but I think it is because of this GitHub issue (maybe someone else can confirm): <https://github.com/gajus/eslint-plugin-jsdoc/issues/901>

Thus, I am pretty stuck, which is why I'm bringing up again the possibility for a specific option, which seems like it might be valuable & general enough to warrant inclusion.

**Comment by brettz9** [comment]
@Zamiell : Try `JsdocBlock:has(JsdocTag[tag="param"])` as your `context`. (Technical note: apparently we should have defined the AST property here as `right` for `esquery` to allow `>` to look for its contents as a "child" rather than a visitor key.)

Am closing as there should therefore be a workaround, but feel free to comment further as needed.
