### ISSUE TITLE
Restore `check-examples` for ESLint 8+

### ISSUE THREAD

**Issue by brettz9** [gajus/eslint-plugin-jsdoc#928]
## Expected behavior

`check-examples` should run on ESLint 8+.

Waiting on https://github.com/eslint/eslint/issues/14745

## Actual behavior

`check-examples` won't run on ESLint 8+.

## ESLint Config

`jsdoc/check-examples: ['error']`

## ESLint sample

N/A

## Environment

- Node version: 16.14.2
- ESLint version: 8.26.0
- `eslint-plugin-jsdoc` version: 39.3.25

**Comment by Jsmithrud37** [comment]
Bump. This is valuable functionality.

**Comment by brettz9** [comment]
As per the OP, we are dependent upon https://github.com/eslint/eslint/issues/14745 .

**Comment by JounQin** [comment]
I don't quite understand what's the root block here, we've already have `text` + nested virtual filenames, maybe you can show more complex example. I'd like to help implement this feature here.

**Comment by JounQin** [comment]
> Is it just that the feature is undocumented but not yet approved by an RFC? 

Yes

**Comment by brettz9** [comment]
@Jsmithrud37 : New docs are available to explain the new alternative for the old `jsdoc/check-examples` rule. It is now implemented as a processor. @JounQin : If you may find some free time, your review of the implementation would be appreciated (especially on why such errors don't seem to show in VSCode), but I think I've at least gotten the essentials working.
