### ISSUE TITLE
`no-types` vs `require-param-type`

### ISSUE THREAD

**Issue by thany** [gajus/eslint-plugin-jsdoc#937]
## Motivation

These two rules appear to be each other's opposite. This is confusing and can lead having two rules contradicting each other.

## Current behavior

These two rules exist, and can both be defined to contradict each other pretty much exactly.

## Desired behavior

Remove one of the two rules.

## Alternatives considered

Just ignore (mentally, that is) one of the two rules.

**Comment by brettz9** [comment]
One issue is that `jsdoc/no-types` also works on `@returns`

**Comment by thany** [comment]
Sure, but that doesn't brush off the fact that it opposes others.

Perhaps then there should be a rule like `require-return-type`.

**Comment by brettz9** [comment]
I think with both the history of the project having acquired certain rules, and with the details inevitably being a little messy (there will always be some inconsistencies), I'm inclined to keep things as they are here.

We could have some configs which automatically enable or disable certain rules (e.g., as is being requested for TypeScript rules), but we need someone to go through and propose specific combinations.

Btw, there is a rule `require-returns-type`.

**Comment by thany** [comment]
Maybe mark `no-types` as deprecated, since you've shown that every of its use-cases are covered by rules specific to them.
