### ISSUE TITLE
Documenting a class causes unexpected required param warnings.

### ISSUE THREAD

**Issue by Faline10** [gajus/eslint-plugin-jsdoc#95]
Documenting a class (whether or not you add @desc/@description in the documentation) requires you to add documentation for any method that is missing documentation for a parameter if the rule "jsdoc/require-param" is on, even though we have not added documentation for those methods at all. e.g. 
```
/**
 * a description
 */
export default class SomeClass {
    _someUndocumentedMethod(aParam) {} // suddenly aParam needs to be documented
}
```
Results in `eslint: jsdoc/require-param - Missing JSDoc @param "aParam" declaration.`
Normally you would only expect to get errors about missing parameters if there is some documentation above a method. like so:
```
 \**
  * some desc that's missing param declaration
  */
 _someUndocumentedMethod(aParam) {}
```
This seems like a bug to me. Can you please confirm if that's the case?

**Comment by brettz9** [comment]
I'm not seeing this as a problem now in `master`. Can you confirm, @Faline10 ?
