### ISSUE TITLE
validate extra useless space

### ISSUE THREAD

**Issue by tjx666** [gajus/eslint-plugin-jsdoc#954]
## Motivation

For beauty, can remove the extra useless space by auto fix.
I want to use this rule to replace https://github.com/hosseinmd/prettier-plugin-jsdoc.

## Current behavior

<img width="821" alt="image" src="https://user-images.githubusercontent.com/41773861/214565904-bd048a9f-c94f-4db8-8715-e92ce0b77fe5.png">

## Desired behavior

<img width="645" alt="image" src="https://user-images.githubusercontent.com/41773861/214566232-85a6b6db-bedb-4b83-baf8-b902eb933a56.png">

**Comment by brettz9** [comment]
Have you tried the `jsdoc/check-line-alignment` rule (set to "never")?
