### ISSUE TITLE
`sort-tag` default rules not working with `@typedef` for `@property`

### ISSUE THREAD

**Issue by thernstig** [gajus/eslint-plugin-jsdoc#957]
## Expected behavior
I would expect the default `sort-tag` order to not sort `@typedef` when it is followed by a `@property` or `@member` tag.

## Actual behavior
`sort-tag` used with `--fix` moves a `@typedef` that exists just before a `@property` (or `@member)` and places it before `@param`.

## ESLint Config

```js
{
  "root": true,
  "reportUnusedDisableDirectives": true,
  "parserOptions": {
    "ecmaVersion": 2023,
    "sourceType": "module"
  },
  "env": {
    "node": true,
    "es2022": true
  },
  "extends": ["plugin:jsdoc/recommended"],
  "rules": {
    "jsdoc/sort-tags": "warn"
  },
  "settings": {
    "jsdoc": {
      "mode": "typescript"
    }
  }
}
```

### Before
```js
/**
 * Test
 *
 * @param {string} test1 - Test
 * @typedef Result
 * @property {string} test2 - Test
 * @returns {string} Test
 */
function reconcileAlertRuleAtUpgrade(test1) {
  return test1;
}
```

### After

```js
/**
 * Test
 *
 * @typedef Result
 * @param {string} test1 - Test
 * @property {string} test2 - Test
 * @returns {string} Test
 */
function reconcileAlertRuleAtUpgrade(test1) {
  return test1;
}
```

This gives the following error from TypeScript:

> JSDoc `'@typedef'` tag should either have a type annotation or be followed by `'@property'` or `'@member'` tags.ts(8021)

## Environment

- Node version: v18.12.1
- ESLint version v8.31.0
- `eslint-plugin-jsdoc` version: 39.6.4

**Comment by brettz9** [comment]
Please always provide the code sample

**Comment by thernstig** [comment]
@brettz9 I should have known better. Update the original post.

**Comment by brettz9** [comment]
I don't think this is actually an issue from the perspective of this rule. `@typedef` (or if you used the more precise `@callback`) is meant to stay toward the top as it gives the overall picture of what the block is that one is looking at.

You can provide your own `tagSequence` if the ordering is not to your taste, but there is no logic which makes the order dependent only on specific tags. It always sorts in a given order, and I don't see there being a compelling need to change this.

**Comment by brettz9** [comment]
Closing as I think this is simply a preference matter, though feel free to comment further as needed.

**Comment by thernstig** [comment]
Ok, fair stance @brettz9, thanks. I will comment further in the future if I come up with some smart reason why something should change.
