### ISSUE TITLE
Unrecognized JSDoc tag: hideconstructor

### ISSUE THREAD

**Issue by jugglinmike** [gajus/eslint-plugin-jsdoc#96]
[JSDoc defines a tag named `hideconstructor`](http://usejsdoc.org/tags-hideconstructor.html), but the tag is not recognized by this plugin, e.g.

    /home/mike/projects/oss/cheerio/cheerio/lib/cheerio.js
      28:1  error  Invalid JSDoc tag name "hideconstructor"  jsdoc/check-tag-names

    ✖ 1 problem (1 error, 0 warnings)

It may be omitted because it's relatively new, having been [introduced in July of last year](https://github.com/jsdoc3/jsdoc3.github.com/issues/168).

For folks looking to work around this in the short term: use the plugin's `additionalTagNames` configuration:

    "settings": {
      "jsdoc": {
        "additionalTagNames": {
          "customTags": ["hideconstructor"]
        }
      }
    }

**Comment by gajus** [comment]
Can you raise a PR?

**Comment by jugglinmike** [comment]
Thanks!
