### ISSUE TITLE
No release notes on latest releases

### ISSUE THREAD

**Issue by JoernBerkefeld** [gajus/eslint-plugin-jsdoc#973]
Well, see for yourself. 
Hard to decide for/against an upgrade if there is no mention of what was changed

**Comment by brettz9** [comment]
I am seeing the releases listed at https://github.com/gajus/eslint-plugin-jsdoc/releases indicating changes, though:

1. The latest GH action we are using apparently does not format as Markdown (I've asked @gajus about this)
2. There were a couple releases where there were some semantic-release errors and they didn't really add anything new.

**Comment by JoernBerkefeld** [comment]
For me it clearly states "no description"

**Comment by brettz9** [comment]
Here's what I see:

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/20234/216777596-18b93e03-7601-47bd-8462-f3943f4df078.png">

Are you looking at the same page?

**Comment by JoernBerkefeld** [comment]
looking at this on my laptop now, it does show the same. on github's android app none of that was visible - and when I checked here before same was true. maybe a glitch in github itself then? I'm glad that my initial report turns out to be wrong! :)

with that said, it shows that these messages were auto-generated from commit messages and not curated. certainly less easy to understand whats going on than before.

**Comment by stof** [comment]
Release notes are indeed missing in the github release.

What is visible in the web version of github is a fallback showing the commit message of the commit being tagged (which won't display the full list of changes if there are multiple commits since the last release)
