### ISSUE TITLE
Remove leading empty lines in descriptions.

### ISSUE THREAD

**Issue by jespertheend** [gajus/eslint-plugin-jsdoc#982]
## Motivation

VSCode automatically adds an empty line at the start of JSDoc comments, but I don't necessarily always want to add a description, so sometimes I end up with comments like these:
```js
/**
 *
 * @param {number} x
 */
function functionWithClearName(x) {}
```

## Current behavior

No errors.

## Desired behavior

An error with autofix that removes the empty line:
```js
/**
 * @param {number} x
 */
function functionWithClearName(x) {}
```

## Alternatives considered

I'm using `match-description` for now:
```js
"jsdoc/match-description": ["error", {
	matchDescription:"^\\S",
	message: "JSDoc comments may not start with an emtpy line.",
}],
```

**Comment by brettz9** [comment]
What do you want to happen to:

```js
/**
 *
 */
```

And under what circumstances does VS Code add an extra line? I think our `jsdoc/require-param` may do so when params are missing; is this the circumstance or can you reproduce under other conditions?

**Comment by jespertheend** [comment]
Completely empty comments can be left as is for me personally, I've never run across that situation yet.

I don't have `jsdoc/require-param` enabled so that's not the case for me.
VSCode adds the empty line when you type `/**` and hit enter above a function like so:

https://user-images.githubusercontent.com/2737650/216795240-4d44833d-404f-4596-b6ce-8dc518f9a1fd.mp4

You can use `tab` to jump to the next section, which gives you a chance to delete the extra line in case you don't want a description.

But I often run across the situation where two parameters have the same type:

https://user-images.githubusercontent.com/2737650/216795260-ff5c2870-fb87-4978-a427-ca17d12df5f8.mp4

In that case I use ⌘⌥⇧↓ to select the second type, but once you've done that `tab` no longer jumps to the empty line so I often forget to remove it.

**Comment by brettz9** [comment]
I'm guessing you must have some other extension installed or something because typing `/**` and hitting enter above a function with a parameter does not add the parameter for me in VSC.

**Comment by jespertheend** [comment]
I'm trying it on https://vscode.dev/ in an incognito window, and while I am able to get it to work without changing any settings, it seems rather unpredictable. I think it needs to load TypeScript first or something. But once it works it keeps working even after refreshing.

I also can't get it to work without saving a file to disk and then opening it. And it seems to need at least some references to types for it to start downloading TypeScript. I'm using a file with the following contents:
```js
/**
 * @param {number} x
 * @param {number} y
 */
function foo(x,y) {

}

function bar(x, y) {

}
```

**Comment by brettz9** [comment]
@thernstig : Thanks, added in #1016

**Comment by thernstig** [comment]
@brettz9 how about auto-generating the table from https://github.com/gajus/eslint-plugin-jsdoc/blob/main/src/index.js? :)

**Comment by thernstig** [comment]
@brettz9 yeah I figured, I think I made a few comments about that part not being updated so it seems missed at times.
